### ISSUE TITLE
make an option to reconnect to geth pipe

### ISSUE THREAD

**Issue by SnaiLiuS** [almindor/etherwall#10]
sometimes geth starts very slow and wallet cant connect to it. make an option to manual connect to geth

**Comment by almindor** [comment]
This is already there. You need to click the bottom right "net bars" icon to reconnect.

**Comment by almindor** [comment]
Added a FAQ entry too

**Comment by SnaiLiuS** [comment]
Here is the log at startup:
Unable to establish IPC connection to Geth. Fix path to Geth and try again.
Checking to see if there is an already running geth...
Etherwall starting

Status bar shows: "Starting Geth" and net icon is disable but geth is syncing :)

**Comment by almindor** [comment]
Hmm did the geth log show the `IPC endpoint opened`? I noticed that geth sometimes gets "stuck" in a state where it just doesn't open the IPC.

If it did then it's an etherwall issue.

**Comment by SnaiLiuS** [comment]
i will check and include a log when this "bug" occure

**Comment by SnaiLiuS** [comment]
confirmed. geth shows "IPC endpoint opened" 3 sec later after etherwall message:
Unable to establish IPC connection to Geth. Fix path to Geth and try again.
Connecting to IPC socket \\.\pipe\geth.ipc

Net icon and other tabs disable. Geth is syncing normal, but etherwall is not reconnect to geth pipe and status bar shows "Geth is starting..."

**Comment by almindor** [comment]
Ok so that means Etherwall times out on waiting for geth and then it seems to try to run it again...

I'll try it on windows with a slow disk to see if I can reproduce.

Just to be clear, you cannot reconnect by clicking the network status icon? (bottom right)

**Comment by SnaiLiuS** [comment]
yes, this icon is disable. in normal situation i can click to it and etherwall reconnects to geth ipc. this situation occures randomly only at start of etherwall.

**Comment by almindor** [comment]
OK thanks for reporting. I think etherwall gets into a funny state after this set of events. I'll have to reproduce to fix.

**Comment by almindor** [comment]
This should now be fixed in version 1.4.2. You may still get the error if `geth` is too slow, but you should be able to click the reconnect button now.

**Comment by SnaiLiuS** [comment]
1.4.2 it works
