### ISSUE TITLE
Error-Invalid name 

### ISSUE THREAD

**Issue by chatov77** [almindor/etherwall#105]
Hello i try to connect to etherwall and i have the error on image.
![0507201818_59_03erro](https://user-images.githubusercontent.com/39337529/42339679-98a698d8-8085-11e8-8d50-3ef1c67025e6.jpg)

**Comment by almindor** [comment]
Are you getting this consistently? I can't seem to reproduce. What OS/version?

**Comment by almindor** [comment]
No reply, closing
