### ISSUE TITLE
Unable to run etherwall v2.2.4 on Kubuntu 18.10

### ISSUE THREAD

**Issue by GrossoMoreira** [almindor/etherwall#109]
Hi, I installed all of etherwall's dependencies and built from source successfully.
However, I can't run the application:
`$ ./Etherwall
QQmlApplicationEngine failed to load component
qrc:/main.qml:315 Type FirstTimeDialog unavailable
qrc:/components/FirstTimeDialog.qml:116 Type SettingsContent unavailable
qrc:/components/SettingsContent.qml:4 module "QtQuick.Extras" is not installed`

I already have qml-module-qtquick-controls version 5.11.1-2, and used it do build etherwall.

Unfortunately I don't have experience debugging Qt issues. Please help.

**Comment by almindor** [comment]
Are you running on the same machine as building? What distro is this?

Did you install all the modules from the readme?

**Comment by GrossoMoreira** [comment]
Yes I'm running this in the same machine as building (on the same directory where I build etherwall, in fact).

Like the title indicates this is on Kubuntu 18.10.

Thank you.

**Comment by almindor** [comment]
This is odd, as far I can say that module should be in the package. I can try installing kubuntu 18.10 in a VM later to see if I can get the same error.

Maybe try asking in kubuntu/ubuntu irc or other forums. There might be something specific about how they package that module.

I'm on Arch so the setup is slightly different for me.

**Comment by almindor** [comment]
Oh wait, did you also try installing `qml-module-qtquick-extras`? [This one](https://packages.ubuntu.com/cosmic/qml-module-qtquick-extras)

**Comment by almindor** [comment]
I guess I missed it, maybe arch has it packaged together, will add to readme.

**Comment by GrossoMoreira** [comment]
Yep, that was it:
sudo apt-get install qml-module-qtquick-extras

Thanks a lot!

**Comment by almindor** [comment]
Closing as fixed, updated readme to address for others.
