### ISSUE TITLE
Want to set up this code on visual studio

### ISSUE THREAD

**Issue by pakistan0021** [almindor/etherwall#111]
Hello every One i want to setup this code to my visual studio

**Comment by almindor** [comment]
I'm not aware of visual studio supporting QT5 projects. Is  there any particular reason why it needs to be VS? You should be able to use QtCreator in windows without any issues.

**Comment by pakistan0021** [comment]
then how i run this source code i am doing reseach on the ether wallet please help me to setup and run this code

**Comment by almindor** [comment]
You should install QT5 and QtCreator. Also make sure to follow the instructions in the README and properly initialize the git submodules.

After that just open the `.pro` file in QtCreator, create a desktop configuration for it and run.
