### ISSUE TITLE
Mac OS X TREZOR USB tranfser freeze

### ISSUE THREAD

**Issue by almindor** [almindor/etherwall#113]
TREZOR devices on Mac OS X fail to send a response back. The "send/recv" transfer function seems to get stuck. Further debugging is needed.

**Comment by bxxwcl** [comment]
In file included from src/main.cpp:36:
In file included from src/accountmodel.h:35:
In file included from src/trezor/trezor.h:14:
src/trezor/wire.h:29:10: fatal error: 'hidapi/hidapi.h' file not found
#include <hidapi/hidapi.h>
         ^~~~~~~~~~~~~~~~~
5 warnings and 1 error generated.
make: *** [main.o] Error 1

**Comment by almindor** [comment]
> In file included from src/main.cpp:36:
> In file included from src/accountmodel.h:35:
> In file included from src/trezor/trezor.h:14:
> src/trezor/wire.h:29:10: fatal error: 'hidapi/hidapi.h' file not found
> #include <hidapi/hidapi.h>
> ^~~~~~~~~~~~~~~~~
> 5 warnings and 1 error generated.
> make: *** [main.o] Error 1

This means you're missing the hidapi package. I think on mac you can do `brew install hidapi`

**Comment by almindor** [comment]
Closing as stale please re-open if not fixed yet.
