### ISSUE TITLE
How do I import an exisiting wallet via passphrase restore?

### ISSUE THREAD

**Issue by thegitfather** [almindor/etherwall#114]
EDIT: Ok I "geth" it now :smile: It's all managed by `geth` commands. I guess a section for importing existing wallets in the README would be nice for people who want to switch their wallet software..

**Comment by almindor** [comment]
Etherwall has two types of backups. A full "wallet-wide" backup that uses a combination of geth encrypted json files (same as yours) + settings and other things which is Etherwall specific.

Then as you mention there's "account import/export" which is per account and is 100% geth. It's explained in the [FAQ](https://www.etherwall.com/faq/#backups)
