### ISSUE TITLE
Transfer from Ethereum Wallet to Metamask

### ISSUE THREAD

**Issue by Winch2** [almindor/etherwall#119]
Hi - I'm sure I'm being v dim though can't find out how to transfer from Etherdyne Wallet to Metamask (I want to buy some GEO). I'd appreciate someone pointing me in the right direction of some advice/support. Thanks, Lars

**Comment by almindor** [comment]
Of course. The accounts are stored with std. `geth` and you can also export them in the same format so you don't need to find the originals. This puts them out encrypted with the password, just so you understand.

You can right click on an account you might want to use elsewhere, export and save the file somewhere. Password stays the same for that account. You can then use MEW or any other wallet that supports Geth accounts to access it by pointing to the file and opening it with your password.

**Comment by almindor** [comment]
Closing the issue, if you encountered problems please reopen.
