### ISSUE TITLE
Will etherwall be ready for the Ethereum 2.0’s Genesis Day on December 1st ?

### ISSUE THREAD

**Issue by Ethorsen** [almindor/etherwall#120]
Title says it all.

I would not want my funds to stay stuck in an outdated client.

Thx

**Comment by almindor** [comment]
No, the funds won't get stuck. There are a few things to understand when it comes to this:

1. Etherwall (the client side) is a front end and still uses `geth` the official client to handle account encryption and operations. This means that even if Etherwall itself stopped working you can still use your account files with other clients or even `myetherwallet.com`

2. The server side is handled by me right now and I keep that updated fairly religiously so things should be fine there. This is the part that's concerned with transaction sending from Etherwall. Even if this failed tho you can switch to another client like I mentioned in point 1.

3. I'm very close to releasing v3 of Etherwall with a UI overhaul, that's the main reason why smaller point releases didn't happen recently. This version will also allow you to easily switch to a completely 3rd party node provider (e.g. Infura) so you can use it even if the Etherwall server drops out.

4. Ethereum 2.0 will not be replacing 1.0 anytime soon, see [this](https://www.coindesk.com/ethereum-2-0-launch-genesis-day-dec-1) for more information on the timing of that.

Hope this answers your concerns.

**Comment by Ethorsen** [comment]
Thank you very much for your efforts in this great project
