### ISSUE TITLE
Etherwall doesn't open and doesn't give me access to my wallet after I exit the program for the first time

### ISSUE THREAD

**Issue by MatteoG98** [almindor/etherwall#121]
Hi! I have uploaded nearly an ethereum on this wallet, for a corrispondence of almost 540€.
I have used the etherwall just once, I have created my account and transfered the money on it. I quit the programm, and after that, with no apparent clear reason, that wasn't going anymore, not letting me access my wallet and my money.
It's never a pleasant experience something like this.
I don't think it's acceptable and it's quite strange that this happened. I didn't do anything wrong in order for it to behave this way.
Please help me to recover my account and my money :)

**Comment by almindor** [comment]
Sorry about the delay, I was out.

Can you please provide more details on the issue? I'm not sure I understand what happened. Does Etherwall not start at all?

I need to also know:

What OS and version you're running
What Etherwall version you have

Your funds should be secure, the important thing is to keep the account files intact and/or make a backup of them to prevent loss in case of disk issues.

**Comment by MatteoG98** [comment]
Hi! Don't worry for the delay.
I improvised myself a pc technician this morning and I was able to access
my wallet through the UTC code, using "MyCrypto" desktop app.
Basically, I use a Windows 10 Os and the Etherwall version was the last one
available on your website.
I used the program only one time, to receive ethereum on it, and then I
closed it.
The programm wasn't able to open itself anymore, saying everytime that it
was missing some system files in order to run, which were actually inside
the folder where the program was supposed to find them.
I tried to download again the programm, and it was not giving me the same
issue, but I was not able to access my previous wallet. I could just create
a new one.
Fortunately I managed to get access to my ethereum and I've sent them to a
friend address. Now they are safe.
I don't know why this happened, it's quite strange and unexpected.
I hope to give you help somehow.

Il Mer 30 Dic 2020, 19:28 Aleš Katona <notifications@github.com> ha scritto:

**Comment by almindor** [comment]
This is really odd. Can you please provide:

1. The sha256 of the etherwall file you downloaded (the zip file, this is to ensure it's the right one)
2. The exact error message, make a screenshot if possible please

What's really strange is that you get the error on second run, but not the first one.

**Comment by MatteoG98** [comment]
Ethereum.zip
<https://drive.google.com/file/d/15M3adRF2ltEVVQSexEoDqijQGLa1Zait/view?usp=drive_web>
This is its original zip file

**Comment by almindor** [comment]
No need for the full file, I just need to know the SHA256 SUM (or any other hash but then please say which one you did). I also couldn't get it due to permissions on your drive.

**Comment by almindor** [comment]
OK I checked the file's SHA sum and it matches ok so this shouldn't be some sort of phishing or other problem like that. Are you able to replicate the issue and provide the error message or screenshot please?

**Comment by almindor** [comment]
Closing as inactive, if you get the error message please re-open.
