### ISSUE TITLE
ERC20 Token send transaction

### ISSUE THREAD

**Issue by arko36** [almindor/etherwall#124]
hi, I have some LINK tokens in the wallet, I can see the balance. I do not know how to send tokens, sorry. I tried with transactions > send Ether but I get and error insufficient funds what am I doing wrong ? do I have to call a contract method ? how ?
Thanks

**Comment by almindor** [comment]
You need to go to the transactions tab and select the LINK token from the drop down (defaults to ETH).

NOTE: you still need some ETH on the account to send out! this is a protocol requirement to pay "gas fees" for the transaction itself. If you don't have any on that account you need to send some.

**Comment by arko36** [comment]
I have an address for the LINK and another for ETH, however, when I try
doing the transaction selecting the LINK address and filling the fields I
do get the insufficient funds error, I assume, it is because I do not have
for the gas but how do I add the ETH for the gas to this LINK transaction ?
I do have ETH in the other eth default address.

**Comment by almindor** [comment]
Yes you need some ETH to pay for sending out the tokens and it needs to come from the address that holds the tokens. So you need both ETH and LINK in that address to be able to send out. This is how things work on Ethereum. Tokens are just "contracts" and any transactions executed on the contract cost ETH in gas fees.

You can get a good idea on how much ETH is needed by trying to construct the transaction first and looking at the cost (total in the transaction dialog). The value of LINK you try to send doesn't affect that.

Send a bit more from your main ETH account to the account with LINK and you should be able to send LINK out.

**Comment by almindor** [comment]
I hope you were able to send your LINK out as needed. Please re-open if you still have an issue.
