### ISSUE TITLE
Host api.etherwall.com not found

### ISSUE THREAD

**Issue by RollMeOneKenob1** [almindor/etherwall#128]
Hi all,

I just downloaded the latest version of etherwall but when I open it I get this error message. Can you please help?

**Comment by almindor** [comment]
Can you please provide your OS type and version?

**Comment by RollMeOneKenob1** [comment]
Hi Aleš,

Thanks for reaching out.

I am not running etherwall on a VM. I have a physical Windows 10 machine
and it is an old build, as I have stopped all kinds of updates whatsoever.

I used to have 2.4 version etherwall on the machine and the last time I
opened it was on 20th of January and it was working fine. I tried again a
few days ago but got an error message.

I downloaded the latest, unziped and copied over the previous installation
but I now I cannot get it to work. TLS initialization failed.
[image: winver.PNG]
BR,

Antonio

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by almindor** [comment]
Closing in favour of #126
