### ISSUE TITLE
Does it support mnemonic phrase?

### ISSUE THREAD

**Issue by R8s6** [almindor/etherwall#131]
Is this something "good to have"?

If so, could it be implemented?

Thanks!

**Comment by almindor** [comment]
Hey, currently no. Etherwall was built in the really early days and uses geth directly for account management. I'll have to check if geth itself added support for this or implement it on the side, but it changes the logic quite a bit on the UI end so it wouldn't be a trivial change.

**Comment by almindor** [comment]
As a side note if you use TREZOR hardware wallet you get HD address generation. That is supported right now.

**Comment by R8s6** [comment]
Thanks. 

After a bit of search, according to [this article](https://support.mycrypto.com/general-knowledge/ethereum-blockchain/difference-between-wallet-types), keystore and mnemonic phrase are 2 different ways to unlock private key, so I guess since we have keystore, it's not necessary to have a mnemonic phrase:

![image](https://user-images.githubusercontent.com/44877866/114769208-c2efb080-9d1e-11eb-9fce-450662b09132.png)
![image](https://support.mycrypto.com/static/5a5a6e6e4b5652f1cbe14bd159503ce1/e8e04/mnemonic-phrase-graphic.png)

Case closed, thanks.
