### ISSUE TITLE
receiving "Socket operation timed out"

### ISSUE THREAD

**Issue by verbal007** [almindor/etherwall#132]
Using latest build of Manjaro (Arch) linux.
Unable to access account.
After I start up Etherwall I received the following message after a few seconds.

"Socket operation timed out."
"<OK>"

Log shows:
Connecting to main Etherwall server
Response parse error: illegal value
HTTP Request error: Socket operation timed out.

**Comment by almindor** [comment]
It appears the whole server where geth is being hosted became inaccessible, I'm currently attempting a hw reset. If that fails I'll have to ask the hosting provider for support tomorrow.

**Comment by almindor** [comment]
The server restarted succesfully, a backup geth node is now in use until the primary syncs back to tip.

**Comment by verbal007** [comment]
> The server restarted succesfully, a backup geth node is now in use until the primary syncs back to tip.

Great.  Thank you!
