### ISSUE TITLE
thin client - not explained how to activate in the software

### ISSUE THREAD

**Issue by slrslr** [almindor/etherwall#133]
Hello,
i wanted to import my existing ETH wallet to a GUI software on Arch Linux and send payment without need to download whole blockchain.

In official repository on Linux i have found etherwall package and went to https://www.etherwall.com/about/ where i read:

> 2. In thin client mode all your account data stays on your computer. A remote ethereum node is used to get latest blockchain information and send signed transaction. 

Ok, now you have not linked to a wiki/FAQ page where is explained how to activate this mode. (can you fix this please and link to https://www.etherwall.com/faq/#thinclient )

Also the above linked FAQ page entry does not jump enywhere (it stays on the page top no matter which link i click) in Firefox 88.0, dev. console shows "Blocked https://www.etherwall.com/faq/ from extracting canvas data because no user input was detected. faq:17:296"

And even that FAQ page does not explain how to do mentioned thing. If you can please fix this too?

I have installed go-ethereum-1.10.2-1 & etherwall-3.0.2-3
I launch the GUI app and it shows additional geth args: --syncmode=fast --cache 512 

$ man geth
No manual entry for geth

$ geth --help|grep sync
  --syncmode value                    Blockchain sync mode ("fast", "full", "snap" or "light") (default: fast)

still nothing, so i have to research using the search engine and now i am thinking that i should possibly use the light mode. I am not sure what is a difference from fast. My aim is to just import my existing wallet and send money from time to time. No more ambitions.

**Comment by almindor** [comment]
You should've been presented with a "first time dialog" when you first started Etherwall. If you didn't switch to "custom node" you should be using a "thin client" mode which means the etherwall server's geth.

Go to settings and make sure Node/Custom Node is unchecked. If it was checked uncheck it and restart Etherwall.

As for the FAQ page, it's done in Wordpress and generated, I don't control the resulting html directly. I simply don't have the time to fix a wordpress issue, running the server and keeping etherwall updates is enough for one person to do for free.

**Comment by slrslr** [comment]
> If you didn't switch to "custom node" you should be using a "thin client"

i do not think i have switched anything, except my setting is:
--syncmode=light --cache 512

and default was:
--syncmode=fast --cache 512

yet in other topic of mine you are saying that i should switch to thin client.

![etherwallsetting-light](https://user-images.githubusercontent.com/6596726/116790505-ff076d00-aaa3-11eb-97b6-f68fd676efb5.gif)

So i am not in thin mode? As mentioned i did no settings change except syncmode=light change described above.

**Comment by almindor** [comment]
Additional geth args are only used when using a custom node in `local geth` mode (in the node groupbox area).

Your settings look ok. Is your issue that your account is showing up but showing an empty balance then? Could you also please show your app log (there's a copy to clipboard button). You can revise the contents before pasting here of course to remove anything you might deem as identifying information.

**Comment by slrslr** [comment]
Thanks for help, it was my fault, i have imported wrong file.

Regarding non working anchor links like https://www.etherwall.com/faq/#thinclient


not sure if your FAQ page in wordpress can be HTML code edited (if you ar enot using any addon to generate page, then there is a HTML tab on the edit page and the HTML should be:

index of topics:
`<a href="#thin-client">Thin client</a>`

thin client section:
`<a id="thin-client">Thin client</a>`

also on the https://www.etherwall.com/faq/#thinclient may be replaced:

> synced node are sent to a remote server.

by

> synced node are sent to a remote server. **Thin client mode is enabled by default** an disabled when XY.

and on the https://www.etherwall.com/about/ may be replaced:

`In thin client mode all your account data`

by:

`In <a href="/faq/#thinclient">thin client mode</a> all your account data`

**Comment by almindor** [comment]
> Thanks for help, it was my fault, i have imported wrong file.
> 
> Regarding non working anchor links like https://www.etherwall.com/faq/#thinclient
> 
> not sure if your FAQ page in wordpress can be HTML code edited (if you are not using any addon to generate page, then there is a HTML tab on the edit page and the HTML should be:
> 
> index of topics:
> `<a href="#thin-client">Thin client</a>`
> 
> thin client section:
> `<a id="thin-client">Thin client</a>`
> 
> by the way https://www.etherwall.com/faq/#checksum works (it jumps to right page location)
> 
> also on the https://www.etherwall.com/faq/#thinclient may be replaced:
> 
> > synced node are sent to a remote server.
> 
> by
> 
> > synced node are sent to a remote server. **Thin client mode is enabled by default** an disabled when XY.
> 
> and on the https://www.etherwall.com/about/ may be replaced:
> 
> `In thin client mode all your account data`
> 
> by:
> 
> `In <a href="/faq/#thinclient">thin client mode</a> all your account data`

Thanks for the suggestions. The hrefs don't work because the destination tags got lost, this is due to wordpress and how it mangles pages when you save, it happened a couple times on updates so I honestly stopped caring. I planned to remake the page in something more static but never got around to it.

I'll update the FAQ contents to reflect the new version process.
