### ISSUE TITLE
How to import ethereum wallet to etherwall?

### ISSUE THREAD

**Issue by slrslr** [almindor/etherwall#134]
Hello,

in the GUI i searched how to import my existing wallet created years ago using https://www.myetherwallet.com or site like that to [Etherwall ETH wallet GUI software](https://www.etherwall.com/about/) etherwall-3.0.2-3.
The "Import" menu entry was looking for .etherwall files so i guess i can not use it.
I have tried to click "New account" hoping there will be import function, but no, it created new wallet set as default.
I have found my backup file UTC--2016-xx-xxTxx-xx-xx.0--walletaddress
and i have copied it to /home/myusername/.ethereum/keystore/ folder
quit, start etherwall and it found the wallet, but shows it as empty, which is wrong and set as not default. My additional geth args: --syncmode=**light** --cache 512
On the Transactions tab, Send Ether, i set recipient 0x35115a19f77816ab262c7cfa3ac7c0b6b87e7049 and value and it says send Input errors, [Address checksum mismatch](https://www.etherwall.com/faq/#checksum)

How to proceed now please, can the import menu entry have some explanation how user can import any ETH wallet?

**Comment by almindor** [comment]
Etherwall's import function is meant for "wallet-wide" export made by Etherwall in the past. You did the correct thing by copying the account file (json) into geth's data path. The problem you have is that because you're not using "thin client" your local geth is our of sync.

You have to either switch thin client on (see other issue for explanation) or have your local geth sync up to tip. I would recommend the thin client since a full sync takes hours and gigabytes.

**Comment by slrslr** [comment]
[I hope that i am already in thin mode](https://github.com/almindor/etherwall/issues/133#issuecomment-830667542) so i do not know why it does not work or how to sync local geth.

**Comment by slrslr** [comment]
The mismatch seems to be due to wallet or geth unable to handle the input address properly.
Etherscan converts the address when i open the https://etherscan.io/address/0x35115a19f77816ab262c7cfa3ac7c0b6b87e7049 it change some normal case letters to upper case (capitals). It is confusing, and despite this issue is closed, i think the the import can be handled differently so i could import the mentioned file "UTC--date-time-walletaddress" via GUI.
