### ISSUE TITLE
Import from keystore file

### ISSUE THREAD

**Issue by PocketSam** [almindor/etherwall#135]
Hello. Can you make an option to import my wallet from keystore file?
Semes like it's very unpopular feature and probably I miss something. But it may be useful to develop such feature or make an article about how to import such wallets.

**Comment by almindor** [comment]
Do you mean geth account files? (the ones that begin with UTC--<DATE> and contain a json)

Adding that is pretty simple since it's just a matter of copying them over to the right folder. For any external wallet custom formats, it'd be another issue completely.

**Comment by PocketSam** [comment]
> Do you mean geth account files? (the ones that begin with UTC-- and contain a json)

Yes, exactly! So no import process required, I should only copy them somewhere and the app would see them?

**Comment by almindor** [comment]
> > Do you mean geth account files? (the ones that begin with UTC-- and contain a json)
> 
> Yes, exactly! So no import process required, I should only copy them somewhere and the app would see them?

Yes, you copy to the `<datadir>/keystore` subfolder. You can find out what your datadir is by looking at settings in etherwall it's the `Geth Data Directory` line.

**Comment by PocketSam** [comment]
Thanks! I hope it would work. =)
