### ISSUE TITLE
"Unable to establish IPC connection to Geth... "

### ISSUE THREAD

**Issue by verbal007** [almindor/etherwall#142]
When launching Etherwall Ethereum Wallet 3.0.3 on latest build of Manjaro, it is not able to connect to the wallet but instead displays the following error:

"Unable to establish IPC connection to Geth. Fix path to Geth and try again."

**Comment by almindor** [comment]
This happens if geth isn't running for some reason. Do you have `geth` installed an is `Geth Path` in settings tab correct? If so check the logs to see if geth itself doesn't show errors.

**Comment by verbal007** [comment]
While running geth from terminal, I did eventually get it to execute and it started to sync.
I then copied these flags, that were listed in Etherwall:
`--syncmode=fast --cache 512
`
This presented me with the following error:
`invalid value "fast" for flag -syncmode: unknown sync mode "fast", want "full", "snap" or "light"`

So I tested this in the terminal, substituting "fast" to "light" and all was good.

I then changed this option in Etherwall's Geth args and...  problem resolved.

I've never messed with these settings, so not sure where this invalid "fast" setting came from.

**Comment by almindor** [comment]
Ah this might actually be a bug. The `--syncmode fast` flag was the original default in older versions of geth and got replaced by `--syncmode snap` now. By default when using Etherwall in "thin client" mode geth is only used to handle account encryption and operations so Etherwall disables syncing, but a syncmode flag was always provided.

I've added code to replace the `fast` with `snap`. Sadly you overrode your settings already so I can't get the values to see why that replace failed. I'll have to look at all the places it might have happened.

**Comment by almindor** [comment]
> I have another machine w/ same OS that also has Etherwall. I just started it up and seeing the exact same issues. How can I help test?

If you still didn't fix this manually please copy your `~/.config/Etherdyne/Etherwall.conf` file and send the contents of `[geth]` `[node]` and `[program]` sections (do not send the others as they contain your address and tx info). This will help me see which arg didn't get fixed and I can try on my local. Thanks!

**Comment by verbal007** [comment]
Gotcha.  Sounds like you might have found the source. Let me know if you still need the config info from my other machine. Might take me a day or two to get to it.

**Comment by almindor** [comment]
> Gotcha. Sounds like you might have found the source. Let me know if you still need the config info from my other machine. Might take me a day or two to get to it.

If you do get the args line it'd be good to confirm it all works but I think we're good without it.
