### ISSUE TITLE
Etherwall cannot be execute in Ubuntu 16.04.1 LTS.

### ISSUE THREAD

**Issue by mochechan** [almindor/etherwall#16]
Etherwall cannot be execute in Ubuntu 16.04.1 LTS, after compiling it.

$ ./Ethereum
QQmlApplicationEngine failed to load component 
qrc://main.qml:22 module "QtQuick.Controls" is not installed.

How to solve this problem? thanks.

**Comment by almindor** [comment]
I think you need to install `qml-module-qtquick-controls`

**Comment by mochechan** [comment]
Thank you very much. Etherwall can be compiled, and it runs in my ubuntu now.
