### ISSUE TITLE
add geth 1.5.5 support

### ISSUE THREAD

**Issue by SnaiLiuS** [almindor/etherwall#17]
v1.4.7 doesnt work with geth 1.5.5

**Comment by almindor** [comment]
Hey, are you referring to the removed `--support-dao-fork` commandline option? Geth seems to have removed it silently without incrementing the major version.

I've removed it in the `v1` branch, if you confirm it's that I'll release a new version. You can look at logs/geth to see what error it writes out.

**Comment by almindor** [comment]
closing this issue as 1.4.8 should've fixed it. reopen if still an issue
