### ISSUE TITLE
How to compile from source?

### ISSUE THREAD

**Issue by wenqingyu** [almindor/etherwall#19]

**Comment by almindor** [comment]
It's mentioned in the main README

Open a terminal and navigate to the root folder of etherwall. Then run:
```
qmake -config release && make
```

Note that this is an "in place" build. You'll get the binary result right in the folder.
You need QT5 installed for this to work (5.6+)

Please confirm if you got it to work, I'll leave this issue open until it's working for you.

**Comment by almindor** [comment]
README has been updated as new requirements have been added.
