### ISSUE TITLE
Wrong download links on the website 

### ISSUE THREAD

**Issue by QuiverNAY** [almindor/etherwall#28]
Hi,

At the download page https://www.etherwall.com/downloads/
platform image is download link as well, but it points to an old version:
`<a href="https://github.com/almindor/etherwall/releases/download/v1.5.0/etherwall_1_5_0.zip"><br>
<img src="https://www.etherwall.com/wp-content/uploads/2017/05/win_logo.png" alt="" width="200" height="200" class="alignleft size-full wp-image-65"></a>`
The same for all other platforms as well.
Actually it'snot a got spot for such issue, however did not find any other contacts on the site.

Thanks,
Andrey

**Comment by almindor** [comment]
Thanks! This is exactly the right place.

I've fixed the image links and will make sure to update them properly in the future :)

Thanks again.
