### ISSUE TITLE
Importing wallet from Mist - Not working

### ISSUE THREAD

**Issue by gwv457vbw4rrt** [almindor/etherwall#31]
Maybe I'm doing this wrong, but I am trying to import a wallet I backed up from Mist and it isn't working. Etherwall says import successful but the wallet never appears in the list. Is there some extra step I need to do?

**Comment by almindor** [comment]
Hey, how exactly did you export the mist wallet in the first place?

What are you doing to import into Etherwall?

The "backup" of Etherwall is meant only for Etherwall and is not compatible with Mist.
Mist however uses Geth the same as Etherwall does so you should be able to get the accounts easily.

Is this on the same computer as Mist was on or on another one? What OS?

**Comment by gwv457vbw4rrt** [comment]
Both on the same machine, windows 7. I'm using a copy of the key file from Mist, the one it points to when you go to Backup>Accounts. Looked at both it and an etherwall export in a text editor and of course they're totally different.

Question I guess is how to I get the ether from Mist to Etherwall without just sending it to myself?

**Comment by almindor** [comment]
When you look at Mist's Backup>Accounts do you get a folder with files named `UTC-<timestamp>-<address>` ?

If so these are correct (JSON encrypted private keys).
What is the folder you have them in?

We just need to find out if Mist used a non-default location and move them to where Etherwall expects them.

**Comment by gwv457vbw4rrt** [comment]
Thanks to your hints I figured it out! Yes I have those keyfiles and they are the correct name format.

I had another geth data folder from the mist install on a separate drive. Pointing Etherwallet to the correct folder gave IPC connection errors. Instead, I used the default folder again and manually copied the key files to the keystone folders and all wallets have shown up! Thanks for the help. 

The missing piece of the puzzle was that Etherwall is a frontend for Geth, for some reason it wasn't very clear to me and I thought maybe it uses its own data/config structure. But when you mentioned that these are the correct files and they just needed to be visible by Geth the light bulb went off.

I should also mention that I really love your wallet software. Always-on Mist hammering away at the hard drives and the looooooooong resync time if mist was closed for a few hours was getting tiresome.

Quick humble suggestion: Please keep the UI exactly as it is. It is simple, elegant and looks great with the windows classic theme, all these other wallet with (html? css?) metro-looking interfaces are an eyesore and way too 2017 in a bad way.

Thanks again and cheers!

**Comment by almindor** [comment]
Thanks for the praise! :)

Glad it all worked out.

Don't worry I won't "HTML-ize" the UI it stays Qt5/Qml the only improvements I plan to add are little details like remembering window size between restarts, sortability by columns etc.
