### ISSUE TITLE
Will not run on Windows 2012 R2

### ISSUE THREAD

**Issue by jsirianni** [almindor/etherwall#34]
Which version of Windows are officially supported? The latest build will not start for me. Its gives me an "ms-api-core-heap" dll missing error. I can get a screenshot of the actual error if needed. 

From what I understand, these libraries are OS specific. I can switch version of Windows if required. I am also happy to test all recent releases of Windows if it helps the developers.

**Comment by jsirianni** [comment]
Error message

https://scontent.fdet1-2.fna.fbcdn.net/v/t1.0-9/20525442_10155539856868899_4506461656911294092_n.jpg?oh=026e0aad64c9ab6ff8903a84c4ddde05&oe=5A080199

**Comment by almindor** [comment]
This is a QT5 limitation as far as I can say, please see http://doc.qt.io/qt-5/supported-platforms.html
