### ISSUE TITLE
Official ETC support in Etherwall

### ISSUE THREAD

**Issue by Mr-Beetroot** [almindor/etherwall#35]
Please implement this feature

Perhaps release it as a separate application: Etherwall ETC

Thanks!

**Comment by almindor** [comment]
Hey,

I don't support ETC but the code is GPLv3 open-source and if people provide ETC support via pull requests I might consider it.

There are a few points that need to be addressed:

1. Packaging and releasing a separate Etherwall with the ETC Geth version (Windows & Mas OS X)
2. Running and paying for ETC "thin client" servers (ETC Geth + Nginx)
3. Supporting any specific changes in the RPC/logic that ETC has different from ETH on their client

I don't have time for any of these but if someone steps up I'm willing to support it if they provide all 3 points.

The other option is to fork and release your own.
