### ISSUE TITLE
no transaction entry after block #3976059

### ISSUE THREAD

**Issue by SnaiLiuS** [almindor/etherwall#36]
I cant see any transactions after block #3976059 in transaction history tab.

**Comment by almindor** [comment]
Hmm the server seems to be up to speed. Note that "internal" (contract) transactions are currently not shown unless they are registered directly.

If this was a normal tx can you provide the hash? If you don't want it publicised here you can send me an email to almindor at gmail dot com

**Comment by SnaiLiuS** [comment]
0x7192e57f4206522ca1e124b7a5036f10f7db11f033520998c84e9a7baedc4a30

**Comment by SnaiLiuS** [comment]
currently im syncing at 4102239

**Comment by almindor** [comment]
Ahh good find! I totally missed the scraping service went down! Thanks. Will try and put up some monitoring for this. It should catch up eventually, if it's still not showing tomorrow re-open the issue please.

**Comment by UGatgithub** [comment]
I see the same issue after block #4116101 I currently miss 3 transactions which I find in the blockchain explorer
