### ISSUE TITLE
Is there a default password?

### ISSUE THREAD

**Issue by matcharles** [almindor/etherwall#38]
Sorry to get in touch here but couldn't find an email elsewhere. I don't remember setting up a password when creating my first wallet. I know 99.99% this is useless but thought I might ask if there wasn't a default password or something I might have missed? Otherwise I am lost. Thanks!

**Comment by almindor** [comment]
There is no default password, but an empty password was possible too. Did you just forget yours? I'm afraid if you set up a password and you don't remember anything about it it's impossible (save for some brute force attack by NSA :D) to get it back.

**Comment by matcharles** [comment]
Yeah that's what I was afraid. I thought I didn't input any, but it doesn't work when sending ETH. I usually use Keepass to generate passwords, I must have forgotten to save it afterward! No chance to brute force those. Of well, 1 ETH in the drain! Thanks a lot for coming back to me 👍

**Comment by almindor** [comment]
One thing to note is that there was a but in Geth where in older versions they accepted empty string as password and later didn't. I'm not sure if they fixed this or not. How long ago was it created?

**Comment by matcharles** [comment]
I created it 8 days ago using the latest build 2.0.1? I'm afraid I'm stuck
looking at this coin for eternity haha

**Comment by almindor** [comment]
There are quite a lot of these heh. Sorry for your loss.
