### ISSUE TITLE
Password

### ISSUE THREAD

**Issue by HLevi87** [almindor/etherwall#39]
Dear Github community,
When I downloaded Etherwall, it already had 2 accounts.
I created a new one, for which I set a password, but I recieved the ETH on one of the previously existing accounts.
My question is: how do I recover a password which I didn't set?

**Comment by almindor** [comment]
Hello,

the two accounts you saw had to be created on your computer/user account by some other client prior to installing Etherwall.

Did you ever use Mist or just Geth directly maybe? Etherwall "shares" the default folder with geth/mist for storing accounts so if any of those clients was used before the accounts created then would be picked up by Etherwall.

When it comes to sending the ETH, which address did you send TO? How was this sent? Do you have the transaction hash?

**Comment by HLevi87** [comment]
I did install Mist before Etherwall, but I used the same password for these two, so that should work - it doesn't, though.
I'm really just a beginner who was probably too hasty...

On Sunday early afternoon, I started installing Mist, then I decided to use Etherwall instead. I unpacked it, saw there were two accounts already, created a new one, and then received some ETH from a friend to one of the previously existing accounts. I think he sent it from a mobile app wallet called "Ethereum Wallet".

I obviously sent the wrong account address, because I was tired.
Do you see any chance to do it back?

Wherre can I find the transaction hash?

**Comment by almindor** [comment]
Ok so now we know why it went to the "old" address and how it got there.

How do you know your "new" password doesn't work with the old addresses? Did you try and send out using the same password?

**Comment by HLevi87** [comment]
I actually tried many combinations, I even tried mistakes I might have made, but they didn't work.

**Comment by almindor** [comment]
Hmm well I can't help much with that I'm afraid. you could try using Mist again and see if that works, but I doubt it will as it's using the same method in the background to get the accounts decrypted.

**Comment by HLevi87** [comment]
I kind of let it go already, just wanted to know if I can do anything to save my first mined ETH (RIP). Thanks anyway for trying to help, I appreciate it.

**Comment by almindor** [comment]
Yeah these happen. Sorry for your (his) loss. Always make sure to save your passwords and do a wallet backup so you don't lose crypto.

I'm going to close this, if you find out anything new that partains to Etherwall specifically please reopen.
