### ISSUE TITLE
Hardware wallet support

### ISSUE THREAD

**Issue by ulrichard** [almindor/etherwall#4]
It would be great if hardware wallets such as trezor or keepkey were supported.

**Comment by almindor** [comment]
I agree. However until someone creates a hw solution compatible with ethereum I can't do much about it.

Etherwall is a thin GUI client on top of Geth/Eth itself. It doesn't handle account creation etc. I do want to add account export/import functionality tho, so you can at least put your private keys somewhere else easily without the need to know where Geth stores them on each platform.

**Comment by ulrichard** [comment]
Somebody told me that ethereum uses the same signature algorithm as bitcoin.
Ether is already registered with BIP044 at index 60 : https://github.com/satoshilabs/slips/blob/master/slip-0044.md 
Thus it should be possible to use existing hw solutions such as trezor.

**Comment by almindor** [comment]
I've asked Trezor but got no answer. I guess they don't talk to us little guys (funny coz I'm Slovak and can speak Czech).

The plan is to add QR export for your encrypted account (so even if someone steals the QR/paper, it's still PW protected). I should have this by v1.1.0. Version 1.0.0 is just around the corner with a lot of new features and integrated Geth support.

**Comment by ulrichard** [comment]
looks like it's not as straightforward as I thought, but can be done as demonstrated by  https://github.com/quorumwallet

**Comment by evieira55** [comment]
they have. its called ledger nano s
here is the link https://www.ledgerwallet.com/products/12-ledger-nano-s

**Comment by ulrichard** [comment]
Does the ethereum support of the ledger nano s run anywhere other than their chrome plugin?
I ask, because their BitCoin electrum integration is lagging since they have this chrome app.

**Comment by almindor** [comment]
This is a bit too much work for me at this point. If anyone is willing to tackle this I'll provide full support as much I can.

**Comment by almindor** [comment]
The new geth is now adding HD support where it should be, so I might add support to this when they finalize their designs.

**Comment by almindor** [comment]
Also of note: https://doc.satoshilabs.com/trezor-tech/api-protobuf.html

Sadly there's no higher level C/C++ implementation only python and java so I'd have to implement all the way down to the USB HID.

**Comment by almindor** [comment]
TREZOR is now supported
