### ISSUE TITLE
Missing transactions after block #4116101 

### ISSUE THREAD

**Issue by UGatgithub** [almindor/etherwall#40]
After block #4116101 I currently miss 3 transactions in the history which I find in the blockchain explorer

**Comment by almindor** [comment]
Thanks for reporting again. Same issue as last time, it seems the IPC connection to parity from our "data scraper" service gets severed at times failing the service.

I had a "restart on failure" configured but forgot to put a timeout interval and it cause it to "run out of tries" right away. I've changed the configs now so hopefully things will become more stable.

Closing as the service is catching up again. please reopen if it does happen a 3rd time (let's not hope for the charm tho :D)

**Comment by UGatgithub** [comment]
Last time it wasn't me who reported it ;-)
How long does it normally take until I can see the transactions in the log?

**Comment by almindor** [comment]
currently on block 4144066 catching up as it goes.

NOTE: you need to restart etherwall to get the "missed" ones.

**Comment by UGatgithub** [comment]
I expected an did the necessary restart and, #4147029 was the last missed one which has become available meanwhile! Thanks! Question: Would it be possible to add a column with the block date in the transaction view and the details? Blockchain explorer has the timestamp ...
