### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by UGatgithub** [almindor/etherwall#44]
Just had a runtime error - Etherwall does not like comma (,) instead of dot (.)
![runtime errpr](https://user-images.githubusercontent.com/30733304/29249391-d2c4846a-802e-11e7-917d-3ae7bda07ab9.jpg)
which I can reproduce as shown in the screenshot.

**Comment by UGatgithub** [comment]
Related to this, how should I stop the still running geth? https://ethereum.stackexchange.com/questions/709/how-do-you-stop-a-running-geth-node/24276#24276

**Comment by almindor** [comment]
Hah nice find. I had something like this happen in the early days but thought I fixed it by forcing U.S. locale. Will investigate.

To stop a "lost" geth you have to kill it. In windows use system monitor and find the process and kill there.

**Comment by UGatgithub** [comment]
In Germany we normally use comma, not dot and so I crashed into this one. ;-)

FYI, I also added a screenshot and a question in https://github.com/almindor/etherwall/issues/37 as the currency issue repeats too often ... What I can tell is that opening cryptocompare.com in general takes quite some time here ...

**Comment by almindor** [comment]
Fixed in latest master. NOTE: I have simply made the input validator only accept dot as the decimal separator for now. I'll investigate more locale-friendly options later (2.1+ or so).

Closing this issue will create a new one for the locale-specific support
