### ISSUE TITLE
Missing Transactions

### ISSUE THREAD

**Issue by angel12** [almindor/etherwall#47]
I am currently missing 1 transaction that I sent last night, it shows up in the blockchain explorer, but not in my wallet. I believe I am using thin-client, but cannot find the option in settings to disable it to test that. I am currently running 2.0.1

**Comment by almindor** [comment]
Yes, the server's disk got full, investigating now as it was a big jump.

**Comment by almindor** [comment]
I am resyncing as the chainsize went up to 100+ GB and my server's disk is full. Hopefully the pruned version will be smaller. Will post a note about this on main site too.

Expect a downtime on the thin client up to one day.

**Comment by angel12** [comment]
That would do it. Just as a side question then, how do I disable thin-client mode?

**Comment by almindor** [comment]
In settings/basic click the big thin client button (it should be "red"). NOTE: this will try and download the full 100gb+ chain data to your machine.

**Comment by almindor** [comment]
Fixed, resync made it go down to ~40gb which is good enough for now. I've opened a new issue for providing better support at giving people info about the server status in the future.
