### ISSUE TITLE
Add server status check for thin client

### ISSUE THREAD

**Issue by almindor** [almindor/etherwall#48]
If the thin client server goes off or falls behind we should show an error, lock accounts from transaction sending and send people over to the website for explanation.

**Comment by UGatgithub** [comment]
Is your thin client implementation  using the geth `--syncmode=light` command mentioned [here ([https://www.reddit.com/r/ethereum/comments/721kf2/running_out_of_disk_space_due_blockchain_size/]) or is that another option to run a thin client with Etherwall? My current understanding is that Etherwall uses a different approach as I can't find a folder named `lightchaindata` ..., or?

**Comment by UGatgithub** [comment]
Looks like I can run geth.exe --light in a separate cmd window (Etherwall attached to external geth) or start Etherwall with the option --syncmode=light and now the folder `lightchaindata` got created but I get a "No suitable peers available" when starting Etherwall while after some time block headers appear being added in geth log, so there should be peers. Also the accounts do not show any ether in this mode (yet) and switching to Teansactions view crashes Etherwall with a runtime error so I need to kill geth.exe manually.

**Comment by almindor** [comment]
Thin client just "removes" all chaindata required calls by calling them on a remote node that has the chain-data on the server.
You can see that described in the diagram [here](https://www.etherwall.com/about/)

When it comes to the light mode on geth it's not working correctly yet. They have too many problems and almost nobody runs the light nodes needed so right now it's not usable. It also has other limitations, like not allowing contract watches currently etc.

**Comment by UGatgithub** [comment]
So your thin client development is currently is in front of the light mode development, that's  interesting, thanks for the clarification.

**Comment by almindor** [comment]
I suppose you could say it like that. I made "thin client" mode when light client saw no improvements in almost a year. Decided it's time to do it the other way rather than just keep waiting until eth devs get a move on.

**Comment by almindor** [comment]
Server status implemented

**Comment by UGatgithub** [comment]
Hi almindor, above I reported some bugs when running Etherwall with geth in light mode. My experience is that Light mode works with Mist and Ethereum Wallet once it finds at least one peer which it does better the last weeks so will you pick up on this bugs?

1. Accounts do not show any ether in light mode
2. Switching to Transactions view crashed Etherwall with a runtime error so users need to kill geth.exe manually via task manager.
