### ISSUE TITLE
Sending problem

### ISSUE THREAD

**Issue by Stadius70** [almindor/etherwall#49]
Hello.

I have a very big problem sending a transaction and I'm very worried! I am sending for the first time and I do not know why this problem arises and how to resolve it. I'm sending you a photo to make it clear what the problem is.
I do not understand what the message means: "No key for given address or file"

http://prikachi.com/images.php?images/775/9164775k.jpg

**Comment by almindor** [comment]
this seems like a geth error. Googling for it I found a bunch of people had this problem e.g. [here](https://ethereum.stackexchange.com/questions/8684/error-no-key-for-given-address-or-file-when-unlocking-coinbase-account)

I'm not sure what the root cause is in your case. Have you used a different wallet before? Mist or Geth directly maybe? Did you create your accounts in etherwall?

**Comment by Stadius70** [comment]
Initially, I had tried to install ether-core, but it made a mistake. Then I installed the ethernet. Two translations have been received - no problem. But it turns out I can not send and the money is inaccessible to me right now. What to do, how to solve the problem?

**Comment by almindor** [comment]
What do you mean by ether-core? Mist or Parity wallet? And what do you mean when you say it made a mistake?

I need to know the details.

Also how many accounts do you have visible in Etherwall? are all of them showing the same error if you try to send?

What OS is this exactly? (windows, but which version)

**Comment by UGatgithub** [comment]
And if you used a different wallet, did you backup the private key(s) and import the account(s) to Etherwall?

**Comment by Stadius70** [comment]
I first installed Ethereum-Wallet-win64-0-9-0.exe and then uninstalling it because it was generating a huge database on the disk.
I have two accounts with different passwords. In both accounts I received translations without any problem.
I was trying to send only from the first account. After this mistake, I did not dare try in the second, because I have more money there and I am afraid of something to go wrong.
Operating System - Windows 7 Ultimate x64

**Comment by almindor** [comment]
Ok, can you please specify where exactly you got Ethereum-Wallet from? I don't recognize the client.

Can you also list the files you see when you go to `C:\Users\<your-user-name>\AppData\Roaming\Ethereum\geth` ? Note the path might be slightly different, basically look for the Ethereum folder somewhere in your home.

There should be a `keystore` folder, if so please go in and see if you see two files with the addresses you expect (the two accounts you created).

**Comment by Stadius70** [comment]
http://prikachi.com/images.php?images/797/9164797x.jpg

**Comment by Stadius70** [comment]
http://prikachi.com/images.php?images/801/9164801z.jpg

**Comment by almindor** [comment]
Hmm ok so one thing that pops up is that you have `keystore` folders in both the main Ethereum folder and also in the geth subfolder.

Can you list those as well?

**Comment by almindor** [comment]
So the files we're looking for will have this format:

`UTC--<timestamp>--<address>`

E.g. for my donations one it looks like `UTC--2015-08-12T23-11-21.237620222Z--c64b50db57c0362e27a32b65bd29363f29fdfa59`

Can you check BOTH the `geth\keystore` and just the `keystore` folders? See if your accounts exist in both and if they're the same files.

**Comment by Stadius70** [comment]
http://prikachi.com/images.php?images/811/9164811N.jpg

**Comment by almindor** [comment]
OK so we see 5 accounts here, notice how none of them is the `0xd729f...` that you used for sending out.

Let's see the geth\keystore folder now.

**Comment by almindor** [comment]
Also I just noticed there's another keystore folder in your keystore folder o.O

This is very odd..

**Comment by Stadius70** [comment]
There is nothing here!
Oh no! Where could this file be missing? :((

**Comment by almindor** [comment]
OK so at this point I would look for any files starting with `UTC--` inside the main ethereum folder.

You should be able to do that using the search function. I'd also copy all of the files you find to a new folder somewhere else just to make sure you don't lose anything.

If you do get the same files twice in different subfolders DO NOT OVERRIDE. There's a possibility it was encrypted with different passwords although the timestamps should never match.

**Comment by almindor** [comment]
The file we're looking for gith now is ending with `-7d29f...`

What we want to do is:
1. copy all the account files to a new folder making sure we back them up
2. move any files from other keystore folders to the main keystore folder (the one directly in Ethereum)

If you find the right file and you move it to the main folder I think you should be able to get sending to work again.

**Comment by UGatgithub** [comment]
If a keystore folder in your chaos is empty that's not problematic as long as you did not delete the contents. They may have got created by one or the other wallet which you installed but did not create / import your accounts to, so don't worry about that too much.

**Comment by Stadius70** [comment]
Here are transaction
https://etherscan.io/address/0xd729F2843DE30545E255476c37829A1C8CF098f6

There are no other files with me.
Where could this file be missing?

**Comment by UGatgithub** [comment]
Within Ethereum/geth you seem to have (had) the complete node installed.

**Comment by Stadius70** [comment]
I had Ethereum Wallet installed, but I uninstalled it because of the huge database it was uploading

**Comment by UGatgithub** [comment]
For the accounts related to the transaction the keystore files from 08.08. should be the related once. Don't think there is something missing.

**Comment by UGatgithub** [comment]
You can uninstall the wallet but the chain data etc. is still there, that you have to cleanup manually (once you backed up all the key files).

**Comment by Stadius70** [comment]
Can you once again explain step by step what I need to do, that I am already confused, and that I do not understand English well and I am getting a translator

**Comment by almindor** [comment]
ok I'll try.

The UTC-- files are your accounts. You have multiple `keystore` folders under the Ethereum folder and that's bad.

We need to find ALL the UTC-- files in the Ethereum\* subfolders and copy them over to another folder (something on your desktop for example).

Once that is done list all those files here (from the new folder).

**Comment by Stadius70** [comment]
I searched all subfolders - no other UTS files?

**Comment by Stadius70** [comment]
Other files except those who showed you the pictures - no ... just no!

**Comment by almindor** [comment]
Ok so this is very odd. Etherwall uses geth to get the list of accounts.

You created the `7d29f...` account using the old wallet correct?

Can you try searching for `UTC--` in your whole computer?

**Comment by Stadius70** [comment]
The 7d29f account ... is my first account
Could it be accidentally deleted?
And is it possible to somehow activate again?

**Comment by almindor** [comment]
So there are three problems:

1. We can't find the account file
2. But somehow it shows up in Etherwall's list
3. Sending fails with file not found (confirming issue from 1.)

So I think the account file might still be somehow visible to geth/etherwall but I don't know where it can be. You can only send from accounts you have the "keys" for and the keys are stored encrypted in these files.

Did you do a full computer search for all the files starting with UTC-- yet?

**Comment by Stadius70** [comment]
I may have deleted the file from the beginning after I met the program because I thought it was not an important file. I remember that there was such a moment in the beginning ...

**Comment by UGatgithub** [comment]
Which wallet did you use to create the 7d29f... account?

**Comment by almindor** [comment]
Ah I understand now.

Etherwall creates a "list" of accounts given to it by Geth. You must've deleted the files after running etherwall.

Sadly there is nothing we can do if the file was deleted and you don't have a copy it's gone.

**Comment by UGatgithub** [comment]
There is software to search and undelete files ... if it is not too long ago and worth investing time ...

**Comment by almindor** [comment]
Yes good point, if you have more ETH in the other files too it might be worth the trouble to try and undelete. NOTE: you should limit any disk activity, preferably turn the computer off and get the disk out to a professional. It will cost something but it might be worth it in the end.

**Comment by Stadius70** [comment]
I think it was ... I had already installed Etherwall and then I remember maybe I deleted a file?

**Comment by almindor** [comment]
Yes that would explain why etherwall still shows the account, because it "caches" the accounts it has seen. Sadly it's just an address cache so it can't recover it, you have to get the original file back somehow.

**Comment by Stadius70** [comment]
I'll try a program to recover deleted files

Thanks for your time!

**Comment by Stadius70** [comment]
For the other account where I have money, the file is saved ...

**Comment by almindor** [comment]
Good to hear! Make a backup too just in case. You should be able to send out from that account as long as the file is in the right spot.

If you need to "move" the account to another computer, copy the file to the keystore folder there and Etherwall should pick it up.
