### ISSUE TITLE
Performed a clean install of windows now my ETH is gone

### ISSUE THREAD

**Issue by 777patryk** [almindor/etherwall#50]
I performed a clean install of windows since my PC was having issues and now my ETH is gone. I have two hard-drives and the one with the desktop app wasn't touched. I exported my wallet before and when I imported it now doesnt show my ethereum please help I spent hard earned money on this

**Comment by UGatgithub** [comment]
Ether gone or access to your wallet gone? Did you check for your ether on the blockchain? If you did not touch the HD with the wallet app, it should not be a problem to restore the wallet. Did you run Etherwall as thin client or as full node with downloaded blockchain?

**Comment by 777patryk** [comment]
I ran it as a thin client

**Comment by UGatgithub** [comment]
Where did you reinstalled it to? Same HD, same folder? You have your keystore files?

**Comment by 777patryk** [comment]
I installed it on my D drive and my OS was on my C drive. But now when I look up my wallet on blockchain explorer and the currency is gone as well off that

**Comment by UGatgithub** [comment]
It is gone on blockchain explorer? That wouldn't be good! You mean your blockchain address is empty?

**Comment by 777patryk** [comment]
Yeah its gone on blockchain explorer it looks like my export changed my wallet address

**Comment by UGatgithub** [comment]
but then you should have a new wallet address where the Ether are now which you should be able to access.

**Comment by 777patryk** [comment]
My new wallet address doesnt have the ether

**Comment by UGatgithub** [comment]
I don't believe an export changes the wallet address, something else must have happened. Are you willing to share your public ether wallet address with me so I can have a look at it?

**Comment by 777patryk** [comment]
Yes of course

**Comment by 777patryk** [comment]
0xEd0530329DA1a13253EAC50b41F60f7b732131fA

**Comment by UGatgithub** [comment]
0xEd0530329DA1a13253EAC50b41F60f7b732131fA has had no transactions so far, so it is a new account created by a new installed wallet. You should be able to import the other one into Etherwall.

**Comment by 777patryk** [comment]
I've tried the import and it created a new address and didnt retain the old one

**Comment by UGatgithub** [comment]
I never did it, maybe Almindor can support you

**Comment by UGatgithub** [comment]
Did you retry the import once more, maybe Etherwall needs an account to be able to import another one?!

**Comment by UGatgithub** [comment]
Did you read the FAQ about the naming issue for the backup file? https://www.etherwall.com/faq/

**Comment by almindor** [comment]
Sorry about the delay, github has been giving me 404 on this issue link, not sure what's up.

Can you please provide:
1. specific OS version you use (windows, but which)
2. specific etherwall versions you used
3. the ethereum address where you expect funds to be (if you know it)
4. a detailed step-by-step description of how things went as you wiped your drive.

Sorry for the "re-request" but I need to clearly understand the situation first.

**Comment by almindor** [comment]
Also please describe how you did the wallet backup. Did you use the full wallet backup (using the main menu) or did you right click on your account and exported that?

**Comment by UGatgithub** [comment]
I also had the 404 error from Github, so I could help, strange ...

**Comment by UGatgithub** [comment]
Side question as I reported the bug with the context menu export, is there a difference between the two exports?

**Comment by 777patryk** [comment]
Thanks for the help guys. So in response to almindor 1. the specific version of windows was windows 10 pro
2. Etherdyne Ethereum Wallet 2.0.1 3. https://etherscan.io/address/0x1f9aa65aa215620aa36cc1649b778755f220b740 4. My computer was having issues and it crashed so i did a clean install of windows wiping everything from my C drive but my etherwall account and everything was on my D drive so I didnt think it would be a problem. 5. I did the wallet backup in the wallet by hitting wallet> export and saved that file. I have that file but as you can see that the address is different now

**Comment by almindor** [comment]
OK so a few things to explain:

Etherwall uses "geth" internally to keep track of local accounts (and in case of full client also of the chaindata)

Geth by default uses `C:\<User>\AppData\Roaming\Ethereum` as it's main datadir folder.

Unless you changed your datadir folder on first use, or in settings later, your accounts would be stored in C drive by default.

The exported wallet should be fine tho, it basically takes all the accounts from the datadir folder and stores them as single file along some other metadata.

To answer UGatgithub's side question, the individual account export in the right-click menu is for one address geth account exports only, while the wallet/export gets everything (each account).

Do I understand it correctly that you had the `0x1f9aa65aa215620aa36cc1649b778755f220b740` address in etherwall before the C-drive wipe and when you re-imported the wallet back after the wipe you now have a different one at `0xEd0530329DA1a13253EAC50b41F60f7b732131fA` ?

Also, did you change the default datadir at any point when using etherwall? Do you recognize the `0xEd0530329DA1a13253EAC50b41F60f7b732131fA` address, did you use or create it at any point?

**Comment by 777patryk** [comment]
Yes that is what happened I believe I had two wallet addresses and it does look familiar so did it only back up that wallet and not the other. If so what can I do

**Comment by almindor** [comment]
Hmm well if you only backed up the other one somehow and truly lost the `0x1f..` one then I'm afraid there's not much that can be done.

If the `.etherwall` backup file that you have doesn't contain the account and you didn't back up the geth keystore files (they look like `UTC--<timestamp>--<address>` then I'm afraid your account got lost with the wipe.

What I don't fully understand tho is how did you do different backups? Did you create one address first, made a backup, then created another one (the one with ETH in it) and made a backup one more time?

**Comment by 777patryk** [comment]
I believe I had mist open and that other account may have gotten in the way and somehow the export chose the other wallet over the one I wanted to backup. Is there a way to backtrack a transaction? If i contact the seller?

**Comment by almindor** [comment]
I still don't understand how mist "got in the way" but I suppose it's not possible to figure this out now.

Not sure what you mean by "backtrack" a transaction? You can follow to the original sender on etherscan.io but from what I can see it seems like a big "all-in-one" address from some exchange or such.

**Comment by 777patryk** [comment]
Yeah it was from a company thats annoying at least it wasnt an absurd amount. Was just thinking maybe they could take back the eth from my wallet but I guess once it is deposited then its out of their control.

**Comment by 777patryk** [comment]
Is there any way to contact etherwall to reinstate my wallet I have proof of the transaction

**Comment by almindor** [comment]
So once ether leaves the source it's in control of whoever has the keys.

You had the keys until the C drive wipe (they were stored in encrypted json files).

As for Etherwall, that's basically me :) I'm afraid as with the original sender, I do not have access to your wallet keys. It's all kept only on your computer, which is kind of the point (otherwise I could just empty people's accounts and send the ETH my way).

If you did an etherwall backup when the correct account was in there and you find that backup that should work, but if you didn't, or you lost it somehow then I'm afraid nobody can get to that account anymore.

**Comment by almindor** [comment]
One other thing to try, but I don't think that's worth it considering we're talking about 0.2 ETH is an undelete on the C drive.

But if you reinstalled windows on that drive it's even more difficult and a professional would ask far more than ~60$ you have in that account.

**Comment by almindor** [comment]
I'm going to close this issue now, if you find out more info that pertains to functionality of Etherwall or think this was a bug then please re-open and append.

**Comment by UGatgithub** [comment]
If you have no keystore backup but a backup of the privat key, then there is still a chance, if not I agree with almindor. https://www.myetherwallet.com/#view-wallet-info

The last option then could be that you give/send the backup file to someone whom you trust  to cross check the file.
