### ISSUE TITLE
Unknown error after leaving wallet to sync for a few hours

### ISSUE THREAD

**Issue by mascondante** [almindor/etherwall#51]
The error popup is blank as of 2.0.1. Nothing in the text field. Just a standard title bar and ok button. Not using thin client. Noticed 2.0,2 just dropped. Going to give that version a spin and see what happens.

**Comment by mascondante** [comment]
Also your latest version [post](https://www.etherwall.com/) claims geth 1.6.7 but the title bar in 2.0.2 still says geth 1.6.6.

**Comment by almindor** [comment]
Which version of OS (windows/?) is this?

Can you provide a screenshot?

What exactly happens? Etherwall starts (in full node mode) and you let it sync then you get an empty error?

I'll check on the bundled geth, maybe I put the old one in by accident.

**Comment by almindor** [comment]
Just checked and the packaged version should be 1.6.7.

Can you look at your geth path in settings? Is it pointing to geth.exe in the same folder as Etherwall is or somewhere else?

**Comment by mascondante** [comment]
Here's the [screenshot](http://imgur.com/a/Sdk7Y). It happens while syncing. I haven't been able to fully sync yet partially because when this error throws I believe geth stops working as when I notice, close and reopen there's noticeably more blocks but I could be wrong.

**Comment by almindor** [comment]
Is there any additional info in the logs? See logs/app

**Comment by mascondante** [comment]
Nothing I can see in this session's app log. Do you have logs set to write out to a file somewhere per session? Catching a shy bug that totally freezes the app would be hard to catch otherwise.

I will say I've noticed if I overclock my gpu too high it will stop responding when the GPU resets. But in that case there is no popup. I doubt the two issues are related but I thought I would let you know about that as well. That's more low priority because it's the user's responsibility to keep their card from crashing rather than the developer of an app.

**Comment by mascondante** [comment]
Okay I was able to catch a log without the app totally freezing. I don't spot anything but maybe you'll have better luck. https://ghostbin.com/paste/78cwo

**Comment by UGatgithub** [comment]
I am not sure if this the last log entry is top or bottom of the file but independent of that, I see on both sides the last logged action relates to the currency load function which reminds me somehow to the issue I have with the currency load https://github.com/almindor/etherwall/issues/37
Just an idea, could you create a debug where the currency load can be disabled to check if there is a connection between the freeze and the currency load?

**Comment by almindor** [comment]
Hmm nothing really shows up in the log. When you get the freeze you get a popup and the app becomes unresponsive correct?

I don't think it has anything to do with currency loading, that action is periodic on purpose. I don't even think the error got logged.

**Comment by mascondante** [comment]
Okay it happened again. I noticed the geth log was spitting out something different than the usual imported chain whatever stuff. I scrolled to where that transition from normal activity stops and changed the window size to get a better screenshot (since the geth window won't let me copy to clipboard). The app froze but I was able to take [this screenshot](http://imgur.com/a/n7P1Z).

**Comment by almindor** [comment]
OK so this is a geth bug. Can you take the screenshot and report on https://github.com/ethereum/go-ethereum ?

You can also try to reproduce without Etherwall by just running geth from commandline, but be sure to specify same parameters (you can see them in the app log).

I'll keep this issue open for a while in case we find something else, but it seems geth crashes on your machine.

**Comment by mascondante** [comment]
Hey sorry about the delay. I haven't opened an issue with the Ethereum folks but I did read the diff files from 2.0.2 to 2.0,4. It seems (from my very limited understanding) you've got the code adjusted to catch any mystery bugs.  I just upgraded to 2.0.4 now. If I find that illusive bugger I'll report it back here.

**Comment by mascondante** [comment]
Okay caught it. 
[Geth Log](https://ghostbin.com/paste/ehuhh)
[App log](https://ghostbin.com/paste/hja4v)

**Comment by almindor** [comment]
Hmm seems another geth bug yeah. This one seems to have happened on a syscall. Can you send the geth log to https://github.com/ethereum/go-ethereum ? Maybe search if you can find a similar issue already opened first.
