### ISSUE TITLE
No syncing

### ISSUE THREAD

**Issue by Rob-2017** [almindor/etherwall#52]
Etherwall dont sync anymore :(  after working for like 2 month. Im new to ethermining, i followed an newbie-guide and the choosen wallet was etherwall. so far it did a god job. txns from miningpool i got withhin one hr. but now it dont sync the blocks anymore. it shows conected with up to 8 peers. i see the following errors in Etherwallet/submenu Logs : 
 WARN [ *timestamp] Syncronisation failed, dropping peer    peer=*address  err = "retrieved hash chain is invalid" 
 WARN [ *timestamp*] Syncronisation failed,dropping peer    peer=*address*  err=timeout
 WARN [ *timestamp*] Syncronisation failed, retrying      err "receipt download canceled (requested)
many of this  like 40 in row WARN [ *timestamp*] Header broke chain ancestry  peer=*address* ?number= *blocknumber?* hash=*address* 

i use Etherwall 2.0.2  Geth v1.6.7 on Win10 x64 all updates
any suggestions ?  thnx

**Comment by UGatgithub** [comment]
Dropping peers is a normal process during sync. if the system detects an issue with one or more peers. Normally the system should start syncing again after some time. Did you try to close and restart Etherwall?

**Comment by Rob-2017** [comment]
hi, thx for reply. 

yes i restarted wallet already and let it work all night. i see the number of blocks it needs to  sync and it count up to 14902 atm . ok i switched  to debugmode, i see many things from which i dont know the meaning -.- any special thing i should look at? actually it dont show errors.  just things like reporting getting txnscount or currency infos etc. But i dont get if i realy need to sync blocks. i set 2nd comp to mine at anohter place. i never synced that machine. so no need to sync for miner, and i can switch wallet to thinclient-mode wich seem to work ( i need to wait for next tnx to prove that). so u need to sync only for special purpose? will thinclient work for ever? what 
disadvantage i have with thinclient ? sry  for noob questions :D.

**Comment by UGatgithub** [comment]
You only need to sync for a full node, thin client uses a remote blockchain, so you do not need to sync and have the complete blockchain on your computer. It just got introduced with version 2 of Etherwall. A disadvantage of a thin client is that it does not support the network like a full node (means more centralization) but it might anyhow be the future as the blockchain becomes too big for normal users.

**Comment by UGatgithub** [comment]
You state there are no error so what's the latest block number on your machine?

**Comment by UGatgithub** [comment]
You do not have Ethereum Wallet or Mist installed also, do you?

**Comment by Rob-2017** [comment]
hello,
my Etherwall show 4190998 as latest block. no i dont have the others installed.  in Logs/Geth i see the infos like "starting peer to peer node instance = geth /v.1.6.7-stable-ab56..../windows-amd64/go1.8.3 and loaded most recent local header ... local full block ... local fast block...  chain configuration ... ipc endpoint opened .... udp rlpx listener up... listener up...  then the warnings like posted 
in logs/application  debug/info/warning/error i see only info- and debugnotes no warnings no errors it shows just setup of parameters  and then repeatedly "Sent: {"id":31,"jsonrpc":"2.0","method":"eth_blockNumber","params":[]}
Received: {"jsonrpc":"2.0","id":30,"result":{"currentBlock":"0x3ff316","highestBlock":"0x402e2d","knownStates":"0x0","pulledStates":"0x0","startingBlock":"0x3ff316"}}"

**Comment by almindor** [comment]
Seems like your chaindata got corrupted. This is a geth issue, I've seen it happen sometimes.

You'll need to re-sync. If you're using the defaults (syncmode=fast) it should be able to do so in <1 day unless your computer is slow or your network connection is slow.

NOTE: be careful when deleting the chaindata folder! make sure to not touch your keystore! Best is to do a wallet backup beforehand just to be on the safe side.

**Comment by almindor** [comment]
The other option is to switch to thin client mode and let the Etherwall's geth server handle the chaindata for you, but it depends on your use case of course.

**Comment by Rob-2017** [comment]
ok, many thx to u both. i will reload chaindata. i do first walletexport.  i careful delete chaindata. syncmode is set to fast. should be done in one day.  but my ssd is at 23 GB free space. so sooner or later need to use thinclient or switch to cheap hdd for chaindata . feels like the blocks are generatet faster and faster...

**Comment by almindor** [comment]
If your disk is at 23GB after you delete the old chaindata you don't have enough disk space left. It takes ~40gb right now with pruning (fast syncmode).

I'd just switch to thin client mode.

**Comment by almindor** [comment]
Closing this now, please re-open if you get the same issue after full resync and confirmed free space.
