### ISSUE TITLE
Geth Path/ database Incorrect

### ISSUE THREAD

**Issue by DanNenninger** [almindor/etherwall#53]
I am in need of some assistance in resetting the correct geth path for my Etherwall wallet. I was trying to change the file path of my wallet and now the wallet cannot connect to geth. I opened the contents of the Etherwall application and then clicked on "MacOS" and then am left with "geth" and "etherwall". I have opened the "geth" and tried to copy and paste various pathways that it shows, but I must be typing the path incorrectly. If someone could please help me I would be greatly appreciative. Thankyou !

**Comment by almindor** [comment]
So on macOS X the default path should be `/Applications/Etherwall.app/Contents/MacOS/geth`

It works for me on an installed version.

Good point about the defaults tho, created issue #54 for restore defaults button.

I'll close this issue now, please re-open if the path didn't work for you.

**Comment by DanNenninger** [comment]
In Etherwall settings for "geth" I am in need of the "geth data directory" as well as the "geth path". The app is saved to my desktop. If I open up geth, shouldn't the geth data directory and the geth path be listed there?

**Comment by almindor** [comment]
Geth data directory defaults to `/Users/<username>/Library/Ethereum` You have replace <username> with your actual user name you login with on your mac.

**Comment by DanNenninger** [comment]
It is still unable to establish IPC connection to geth. Wouldn't the exact geth path and data directory be listed in geth if I open Etherwall's file contents?

**Comment by almindor** [comment]
so the datadir is where geth "stores" it's ipc "file" for connecting by default. If you reset both the geth file path and datadir to defaults it should work.
