### ISSUE TITLE
ERC20 tokens (OMG OmiseGo) 

### ISSUE THREAD

**Issue by DanNenninger** [almindor/etherwall#55]
Hello again. I am in need of further assistance with my Etherwall wallet. I made the mistake of sending ERC20 tokens to my Etherwall wallet from Bitfinex. I read online that ERC20 tokens can be stored in your ethereum wallet so I sent some OMG (OmiseGo) tokens to my Etherwall wallet. I checked Etherscan and it shows that the OMG tokens are in the wallet, however I am unable to see them on Etherwall. What steps should I take to recover my OMG tokens? I read online that I could export the wallet into a 3rd party to make the ERC20 tokens visible, but am unsure if this is the best way. Thank you for all of your help, it is greatly appreciated.

**Comment by almindor** [comment]
Don't worry your tokens are safe as long as you have access to your keystore files (and the corresponding passwords!)

Etherwall doesn't currently support ERC20 in a "nice" way. You can't easily check your balance etc.

You can either use Mist/Ethereum Wallet from ethdev directly, or you can export your account and then use something like MyEtherWallet to handle the tokens.

Note: if you use Mist or other full client, and you used the thin-client mode with Etherwall you'll need to let the other wallet download the full blockchain.

Also make sure to do a wallet backup before doing anything, just to be on the safe side. Is your datadir/geth situation fixed now?

**Comment by DanNenninger** [comment]
Thank you so much for the quick responses!! Yes, the datadir/geth situation has been resolved. Now I just need to access my ERC20 tokens. Which method would you recommend that I use to regain access to my ERC20 tokens? I'm relatively new to the crypto world and am always nervous when dealing with wallets.

**Comment by almindor** [comment]
You can use https://www.myetherwallet.com/#generate-wallet to get the account to MyEtherWallet (DOUBLE CHECK THE URL AND CERTIFICATE!!!)

If I remember correctly they have some way of "adding a custom token" to see balances, but I don't use them so not sure.

I found this for a guide: https://myetherwallet.groovehq.com/knowledge_base/topics/how-to-see-a-new-token-in-myetherwallet

DISCLAIMER: I do not know if the information provided in those external pages is safe! Double check everything, find other sources before exposing your account.

To get the account file (the "geth json") right click on your account in Etherwall and export it. Password to unlock remains same.

**Comment by almindor** [comment]
Latest version `2.0.3` now has proper `eth_call` support. While not the full convenience of ERC20 support you can now do everything "manually" in etherwall.

To "register" your token, get the OmiseGo contract address and add it as an existing contract to Etherwall. You can then invoke it and call the `balanceOf` function with your address specified. The transaction portion can stay "default", and you'll see your balance in the results tab.

To send out tokens, use the same process just use the `transfer` method but be sure to specify the owner from address in the transaction setup step. Also make sure to NOT send any Ether in the transaction setup (use 0).
