### ISSUE TITLE
can not start etherwall anymore

### ISSUE THREAD

**Issue by Fluppert** [almindor/etherwall#59]
Hi, I am a total nitwit with this wallet and I a made some mistakes. 
With the start I immediatly copied one of the two codes and bought some Ethereums. Those two codes had no pasword yet. The next time I started etherwall that account number was gone and there were 2 different numbers. I did backup the important account on a stich though. In an attempt to find a solution a changed the geth path and geth directory which was probably a mistake. Whenever I try to start Etherwall I get the message 'could not find get ; please check get path and try again'.  Everything is greyed out exept settings and logs. What are the default settings for Geth Data Directory and Geth Path?
I'd like to access my Ethereums.
Thanks in advance
Philippe

**Comment by Fluppert** [comment]
forgot to say I work with Windows 10
Philippe

**Comment by almindor** [comment]
Hey, I'm not sure I fully understand what you mean "copied one of the two codes" ? Did you copy the account file?

The default geth path for windows is: `<path-to-etherwall>\geth.exe`
The default geth datadir for windows is: `C:\<User>\AppData\Roaming\Ethereum`
NOTE: you need to replace <User> with your windows username and <path-to-etherwall> with the absolute path to the etherwall dir

**Comment by Fluppert** [comment]
yes, I copied the account file.
I'try to change the geth path now

**Comment by Fluppert** [comment]
doesn't work. The system seems to be in a loop now and starts up in new windows over and over again

**Comment by almindor** [comment]
That's odd. Make sure there's no geth running first. Maybe do a fresh reboot and then try from scratch. I know that sometimes geth can go "zombie" in the background and etherwall can get stuck.

**Comment by Fluppert** [comment]
same problem after reboot

**Comment by almindor** [comment]
So the whole app just starts and closes and starts again?? Any chance you can do a screenshot?

**Comment by Fluppert** [comment]
it doesn't close. New windows every second
![etherwall](https://user-images.githubusercontent.com/4161526/30221011-03200e0c-94c2-11e7-8c5d-20c7a39cde25.jpg)

**Comment by almindor** [comment]
Wtf.. that's new. Are you sure you didn't point geth path to Etherwall.exe or something like that?

**Comment by almindor** [comment]
Can you switch to logs/app and do a screenshot there? just pick an existing instance. I want to see what it's trying to run.

**Comment by Fluppert** [comment]
I did :( 
The wallet starts up normally now.
It doesn't show any accounts now though
How do I get to open the account number I saved before?

**Comment by Fluppert** [comment]
I right-clikked on the account and chose 'export account to directory'. Hope this was enough to be able to recuperate it

**Comment by almindor** [comment]
It should be, do you have a file that looks like `UTC--<some-timestamp>--<address>` ? If to you need to copy it in your datadir/keystore folder.

**Comment by Fluppert** [comment]
found it! 
Thanks a lot almindor.
Have my money back :)

**Comment by almindor** [comment]
Glad to hear that, closing this issue.
