### ISSUE TITLE
Etherwall crash

### ISSUE THREAD

**Issue by Tussy007** [almindor/etherwall#6]
Using latest Etherwall 9.0.3 windows & geth
worked like a charm up to now but now chashes as soon i click the transaction tab.

Latest changes, a few sent transaction and seems a sent transaction of 0Eth

Getting a error message : Assertion failed!
Bigint.cpp, line 1724
Expression: 0

**Comment by Tussy007** [comment]
additionally i ddi delete the gas int value on the transacto page to use market price for gas and then closed the app.
Have not been able to use it since

**Comment by Tussy007** [comment]
managed to get it working :)
had to set reg key "Gas" in HKEY_CURRENT_USER\Software\Etherdiene\Etherwall  from 21,000 21000
app missing a validation on save there.

**Comment by almindor** [comment]
Hey,

thanks for the report. It seems this was a locale issue/bug where the value
was stored with a comma and cause a numeric crash.

I'll look into it before releasing 1.0.x to ensure it doesn't happen.

Thanks!

Ales

2016-04-25 6:19 GMT-06:00 Tussy007 <notifications@github.com>:

> managed to get it working :)
> had to set reg key "Gas" in
> HKEY_CURRENT_USER\Software\Etherdiene\Etherwall from 21,000 21000
> app missing a validation on save there.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/almindor/etherwall/issues/6#issuecomment-214290870>
>



-- 
Feel the power of Opensource.
Feel the power of Free Pascal.

**Comment by almindor** [comment]
Are you still experiencing similar issues? If not I'll close this issue.

**Comment by almindor** [comment]
Closing because it's been so many changes since then. If you still experience the crash please reopen the issue.
