### ISSUE TITLE
Connecting to node ...

### ISSUE THREAD

**Issue by UGatgithub** [almindor/etherwall#61]
After installing version 2.0.5 I get a "Remote node undergoing maintenance, thin client not available" warning when starting Etherwall but I am currently not using the thin client and the system gets stuck in "Connecting to node ... without loading accounts, etc. ...
When I use the 2.0.4 Etherwall.exe file instead everything works as in the past.

**Comment by almindor** [comment]
Hey, you are correct. I only noticed recently myself. I've got a fix ready but needed to also fix some changes geth made to getting gas price on an empty (unsynced) node.

The remote node server is still resyncing and I'm really busy right now so chances are the fix won't be out before the node is done (which "works around" the issue).

I'll try to get 2.0.6 out tomorrow.

**Comment by almindor** [comment]
Issue should be fixed with the new 2.0.6 release. Please re-open if you still get problems.
