### ISSUE TITLE
no password

### ISSUE THREAD

**Issue by Fluppert** [almindor/etherwall#62]
Hi,
I am new with this wallet. When you install it for the first time you have already two accounts without setting any password. I probably should have made a new acount but I didn't. I bought some Ethereum right away and I have them into my account. My problem now is I can 't send it anywhere because I am asked for the password and as I said I don't have one. 
Can this issue be resolved?
Regards,
Philippe

**Comment by almindor** [comment]
Hello,

Etherwall uses Geth (the commandline ethereum node/client) same as the official wallet does. This means that when you create accounts, etherwall tells Geth to do so and Geth stores the account encrypted files.

Etherwall does not create any accounts by default. What you got were two accounts that had to be created previously on your computer by either Geth or Mist (Ethereum Wallet) via Geth beforehand.

Are you sure you never ran any other Ethereum wallet before? The passwords would be the ones you used to create those accounts originally. 

You can check out the files to see their creation date and maybe try to remember if you set something up at that time.
If you're on windows the default account file location should be `C:\Users\<your_login>\AppData\Roaming\Ethereum\keystore`

The files are named `UTC--<timestamp>--<address>`

Check the timestamp in the name and the creation time in the file properties to see when they were created.

I'm afraid that if you don't know them there's no way to send anything out.

**Comment by Fluppert** [comment]
Thanks Almindor.
You are right and I did make a password. 
I thought this was from another account but it worked.
Regards,
philippe
