### ISSUE TITLE
Trezor and full node client

### ISSUE THREAD

**Issue by Mr-Beetroot** [almindor/etherwall#64]
Greetings,

![trezor](https://user-images.githubusercontent.com/17420956/31647900-7248b6aa-b33d-11e7-993b-af345931d494.png)

1/ For some reason, when the client is set to full node mode (download all blockchain) the Etherwall software does not connect to Trezor and displays an error message

Does this mean that the full node client is also not working when your servers are undergoing an upgrade?

2/ Is it possible to use the ETH private keys that are stored on Trezor and used with Etherwall with MyEtherWallet via the official trezor website? 

If so, please mention how to find out the correct HD derivation path for a hidden wallet that is set with an offset parameter in Etherwall

3/ When is your server upgrade planned to be finalized? The thin client server has been down for more than 5 hours already on the 17th of October 2017

**Comment by almindor** [comment]
Hey,

1. the HID open error shouldn't have anything to do with full client. What OS are you running on? This error usually means a permissions problem when trying to access the usb device but I also got it on a faulty USB port once.

2. The keys are compatible, offset it literally just the hd derivation path last number. You can specify the number of addresses to load on MyEtherwallet, I'm not sure if they support offset tho so if you used a big number you might have an issue there. You can manually set the number as the last part of the HD path. You can check that on Etherwall too, without Trezor by looking at your address details. The full derivation path is shown in the HD path field in details.

3. The only reason I have to do these "upgrades" is that I'm running out of space on the server. I'm running a linode server with ~90GB space and when geth starts to fill it up I have to resync from scratch to "prune" the old data away and get it under 40gb again. I'm considering moving to amazon as they offer more dynamic options for disk drives but their networking is limited for small instances so it's a bit of a conundrum. You can donate a server if you have one...

**Comment by almindor** [comment]
NOTE: thin client just re-enabled, server pruning done

**Comment by almindor** [comment]
Hmm looking at geth they added direct support for TREZOR devices. I think I might need to disable usb monitoring on geth to ensure Etherwall isn't "beat to the punch" on connecting to TREZOR.

I'll release 2.0.9 with a fix soon but for now try adding ` --nousb` in `settings/geth/additional geth args`

**Comment by almindor** [comment]
Sorry for the confusion here, it seems I have code that's supposed to add `--nousb` to geth to prevent it from "stealing" the TREZOR usb connection but it somehow doesn't end up in the list of arguments actually used so this is indeed a bug.

**Comment by Mr-Beetroot** [comment]
Mac OS X 10.13 High Sierra

The PIN prompt on the Trezor is showing up.
Then Etherwall shows the error message

This is from the Geth log tab:

WARN [10-18|00:28:22] Failed to open wallet
url=trezor://IOService:/AppleACPIPl… err="trezor: pin needed"

wallet.trezor.io works fine and Trezor boots up

If the derivation path is set to the standard with the offset number as the last digits MyEtherWallet does not recognize this format:

m/44'/60’/0’/***

Please implement the updates as soon as possible

I might consider donating a server. What is the approximate cost of this solution?
I also have ideas for UX improvement if you're interested in speaking about it
Can I send a DM to you via Keybase?

Let me access my ETH first though please...

**Comment by almindor** [comment]
2.0.9 released, this should fix your issue. The problem was geth added TREZOR support to the commandline client itself so it was "stealing" the USB connection. I had a `--nousb` flag in code but it didn't make it due to a bug. Please confirm it works for you now.

My keybase is currently registered for a work macbook and I managed to mingle my personal email there so please don't use that right now. I'll sort it out and get back to you on the keybase account in here.

**Comment by almindor** [comment]
You can also use cryptup and send me an encrypted email to almindor [at] gmail (dot) com
