### ISSUE TITLE
Account renaming issue

### ISSUE THREAD

**Issue by UGatgithub** [almindor/etherwall#65]
I have 3 Ether accounts that I named `Ether UG`, `Ether UG2` and `Ether UG3`.

1. `Ether UG2` I renamed to `Augur UG`.
2. When I want to rename `Ether UG3` to `Ether UG2` Etherwall renames `Augur UG` back to `Ether UG2` instead.

I use the Details dialog box for renaming and for me this looks like there is some bug.

**Comment by almindor** [comment]
Hey, would it be possible to have a look at your regexp entries for etherwall? I assume you're on windows.

I only need to see the ones in the [accounts] section which match the hash of the address in question. You should be able to export the etherwall regexp entries into a file and edit that so it only has what I need.

NOTE: etherwall's config never stores any "sensitive" information (e.g. password or password hashes or anything like that). It does store addresses and their config (e.g. names, being default, etc.) and transaction history.

**Comment by almindor** [comment]
I'm not 100% sure I follow your renaming tho.

Ether UG2 being renamed to Augur UG is address "A" correct? Ether UG3 trying to be renamed to Ether UG2 is a different address "B"?

I suppose in this case you're renaming A to something else first and then B to what A used to be called?

**Comment by almindor** [comment]
Oh I see, I got it to happen too now. You can "workaround" for now by using right click menu and doing "alias account name". That way seems to work fine.

I'll work on a fix :) Thanks for reporting.

**Comment by UGatgithub** [comment]
Workaround works correctly, thanks for picking up on the issue quickly!
