### ISSUE TITLE
Please GPG sign your commits

### ISSUE THREAD

**Issue by m-o-e** [almindor/etherwall#67]
It's really easy to setup and then takes zero extra work:

* https://help.github.com/articles/signing-commits-using-gpg/

**Comment by almindor** [comment]
This is now set up. Thanks for pushing for it, I wanted to do this once in the past and then forgot.

**Comment by m-o-e** [comment]
Excellent! Thanks for fixing this and for all the work that you put into Etherwall!

Will feel much better to download the updates now (more confidence that it's the legit binary).
