### ISSUE TITLE
Please GPG sign your releases

### ISSUE THREAD

**Issue by m-o-e** [almindor/etherwall#68]
It's really easy to setup and then takes only a few seconds of extra time per release (scriptable):

* https://wiki.debian.org/Creating%20signed%20GitHub%20releases

**Comment by almindor** [comment]
Good point, will do ASAP.

**Comment by m-o-e** [comment]
Great, thank you! :)

**Comment by almindor** [comment]
v2.1.0 now signed (binaries pending)
