### ISSUE TITLE
Issue Importing JSON File

### ISSUE THREAD

**Issue by drinking12many** [almindor/etherwall#71]
I do not know if it only affects JSON files, but I was trying to import a JSON file and it said it imported successfully. It did not show up in my accounts list though. I then moved the JSON file into the path I specified for the Geth Data directory then imported it again and it worked. It should either give an error when importing from another directory or copy it into the data directory specified.

**Comment by almindor** [comment]
Hey, I'm not sure I understand exactly what you did. The JSON file is a geth account file correct? (UTC--<timestamp>--<address> formatted).

How did you try to import the file? Via wallet/import?

**Comment by drinking12many** [comment]
Yes I tried to import it through wallet/import and it did import as long as
it was in the directory that I specified in the wallet for data, but if I
tried to import it from another folder it said it succeeded but it did not
actually import.

**Comment by almindor** [comment]
Ah I think I understand now. So wallet/import is not meant for individual geth account files, but the exported full wallet backup from Etherwall (the result of wallet/export).

The fact that it said success is a bug tho, it should've failed on format checks. There's currently no individual account import functionality in etherwall, but as you mentioned, copying the files to datadir/keystore will do it.

The distinction between the full wallet backup and individual accounts is described in the in [the FAQ](https://www.etherwall.com/faq/#backups)
