### ISSUE TITLE
Thin Client Sync -  Showing Block #4719376

### ISSUE THREAD

**Issue by N1ck3l** [almindor/etherwall#76]
Hi!

It seems that the thin client is a bit off sync now. Is there any way to check if it's something on my side or is server-side?

Right now is showing for me block # 4719376

**Comment by almindor** [comment]
Hmm good find. On first glance the server's geth node seems fine, accepting single blocks but the number is below the current tip. I think the node either got off and went on a reorg chain or is just behind on peers, will try to remedy with restart and/or resync.

**Comment by N1ck3l** [comment]
Thanks! I found it when I sent a tx and showed up at the network but was not updating at the client. 

During that period I created an account, which I think went ok. We will see as soon as the client updates to the latest block.

**Comment by almindor** [comment]
Seems the node is having trouble importing the cryptokitty blocks. It seems to be on the right chain just goes literally one block by one block.

The machine it's running on has a huge but slower disk, I think this contributes now that it hit the "superbusy" kitty-blocks. It is still going faster than new blocks are made atm. so I'll keep it going for a while. Will issue a warning to users tho. Thanks for reporting.

I'll keep the issue open until it catches up, worst case scenario I'll let it resync from scratch using the pruning method.

**Comment by N1ck3l** [comment]
Makes sense.  Thanks for the heads-up.

_Warning: Kitties are filling the place!_

**Comment by almindor** [comment]
Node is now caught up, the "historic tx" db is still a bit behind but that's not a critical functionality so closing this issue now.
