### ISSUE TITLE
IPC socket location fail on Mac

### ISSUE THREAD

**Issue by rmeruane** [almindor/etherwall#8]
There is a problem finding IPC socket location on MacOS when you choose custom data folder.

<img width="874" alt="screen shot 2016-09-05 at 4 50 31 pm" src="https://cloud.githubusercontent.com/assets/711836/18256244/fb908622-7388-11e6-8334-ec82d6a21ac0.png">

**Comment by almindor** [comment]
Thanks for reporting the issue. Can you please provide the screenshot of settings/basic tab (with the datadir)? It seems it might be the double "//" causing the issue here.

**Comment by rmeruane** [comment]
This is my Settings tab

<img width="903" alt="screen shot 2016-09-05 at 7 44 31 pm" src="https://cloud.githubusercontent.com/assets/711836/18257890/91f248ea-73a1-11e6-9a19-933c3e39637f.png">

The IPC route is /Volumes/Rafael128GB/Ethereum/geth.ipc but the client tries to connect to /User/rafael/Library/Ethereum//geth.ipc

<img width="896" alt="screen shot 2016-09-05 at 7 45 07 pm" src="https://cloud.githubusercontent.com/assets/711836/18257876/604b92ce-73a1-11e6-93f7-4469ade944b5.png">

**Comment by almindor** [comment]
Hmm seems it's always going to the "default" path. I'll create a symlink on my mac to try this out with a custom path and get back to you shortly.

**Comment by rmeruane** [comment]
thanks almindor!

**Comment by almindor** [comment]
Confirmed, the logic was wrong and always went for the default. I have to test all three platforms before releasing 1.3.2.

As a workaround for now you can create a symlink to where Etherwall goes by default.
In your case (in terminal): `ln -s /Volumes/Rafael128GB/Ethereum /User/rafael/Library/Ethereum`

If you want to help test this issue, and are somewhat familiar with building QT5 (e.g. via QTCreator) you can help me  by checking out the `dev` branch, building and using it to see if it works for you now.

**Comment by almindor** [comment]
This should be fixed now with 1.3.2. Please re-open if that's not the case.
