### ISSUE TITLE
pass phrase

### ISSUE THREAD

**Issue by brunoflb21** [almindor/etherwall#81]
i have password and eth address, is there anyway to recover pass phrase. i don't have it and need help accessing my account for sending ether. any help would be appreciated. total screw up.

**Comment by almindor** [comment]
hey, im not sure i understand what you mean by pass phrase? you said that you have the password and address.

Do you mean that you know your password and the addess that it unlocks but you lost the account file?

**Comment by brunoflb21** [comment]
no. i log in using my password. i press send eth button from an address. i enter address and amount to send to. than i am asked for password. i enter my password and i received an error saying pass phrase could not be encryted although it asked for a password initially.

**Comment by brunoflb21** [comment]
![image](https://user-images.githubusercontent.com/12664750/34971305-afce0b6e-fa47-11e7-9f7e-346187770dc8.png)

**Comment by almindor** [comment]
What do you mean by "log in"? you should only be queried about the password on tx sends like the one in your screenshot.

Did you forget the password you used when you created the account?

**Comment by brunoflb21** [comment]
sorry for the confusion. yes you are right there is no log in. originally i had the wrong password. so when i got the passphrase error i was confused. did i make a passphrase as the error states. no. i went through my various passwords and found the correct one. thanks for your quick response. the passphrase error threw me off, and i'm new to this so my apologies. program works fine once the operator has his act together.

**Comment by almindor** [comment]
Good to know! Closing issue.
