### ISSUE TITLE
last block only 5090665

### ISSUE THREAD

**Issue by SnowLeopard71** [almindor/etherwall#85]
My wallet, in thin client mode, is reporting the latest block as 5,090,665 but the latest as I write this is 5,092,138.   The log tabs show no errors.
What can I do to get it up-to-date?

**Comment by almindor** [comment]
Good catch. `geth` on the server got stuck for some reason and stopped syncing. Restarted. It should be caught up pretty soon.

**Comment by almindor** [comment]
Should be all caught up now
