### ISSUE TITLE
Etherwall bugs when running geth in light mode

### ISSUE THREAD

**Issue by UGatgithub** [almindor/etherwall#86]
Hi almindor, [here](https://github.com/almindor/etherwall/issues/48) I reported some bugs when running Etherwall with geth in light mode. My experience is that Light mode works nowadays with Mist and Ethereum Wallet once it finds at least one peer which it does better the last weeks so my question:

Will you pick up on the following two bugs:
1. Accounts do not show any ether in light mode
2. Switching to Transactions view crashed Etherwall with a runtime error so users need to kill geth.exe manually via task manager.

**Comment by almindor** [comment]
Light mode is still considered experimental. The accounts not showing balance is most likely either the light client (geth) not being synced fully yet or bugged (e.g. a bad fork).

I'll check out the crash, I suspect it's related to geth giving some unexpected value in a reply when in light mode.

I'm not planning supporting light mode until it becomes more stable and synchronization is possible. There are also contract-related issues with light mode right now.

Will keep this issue opened until I confirm the tx tab crash.

**Comment by almindor** [comment]
I just ran geth in a separate terminal with `geth --light` and used Etherwall with it. Everything seems to work ok as long as you let it connect to peers first. My balances are ok and I could go in the transactions tab as well.

Which version of Geth did you try `--light` with? I'm using `1.8.1`

**Comment by UGatgithub** [comment]
Etherwall under Windows is completely synced (as I said, works with Mist and Ethereum Wallet) and also syncs when I start Etherwall with Additional Geth args:
`--syncmode light -verbosity 3 --cache 2560 --maxpeers 25 --identity NodeUG`

![image](https://user-images.githubusercontent.com/30733304/36693722-7c8fbd4a-1b3c-11e8-895d-a9df23f35f12.png)

**Comment by UGatgithub** [comment]
Did a test and can confirm it works when I launch `geth --light` in a separate PowerShell Window, so the issue only exists when using the Etherwall internal Additional Geth args setup possibility.

**Comment by UGatgithub** [comment]
When you update Etherwall, take care about the correct syntax (see here: https://gist.github.com/marcialwushu/693bcea078b27fa51daa02c1b94a7e37). Sometimes the writing in Etherwall does not work as expected. Example:

**Comment by almindor** [comment]
This is interesting since `--light` should equal `--syncmode light`.

Reopening. I'll try and reproduce the crash.

**Comment by UGatgithub** [comment]
Thanks for picking up and reopening, I think I closed it by accident.

**Comment by UGatgithub** [comment]
Yes, in Etherwall ‘--light’ gets change automatically to ‘--syncmode light’ but ‘syncmode “light”’ which is the way to enter in the command in Windows PowerShell gives an error and if used within Etherwall as Additional Geth argument.

**Comment by almindor** [comment]
Hmm can't seem to reproduce on linux. Can you send me your full app logs? It'll contain the geth commandline used so I can be sure i'm using the same combination of params (get the one with syncmode light when it crashes).

**Comment by UGatgithub** [comment]
Yes, verbosity 3 or higher?

**Comment by UGatgithub** [comment]
This is an old thread but partly still valid. Meanwhile I tested again and can run geth in light mode via Etherwall and once it finds peers, it also syncs up to the actual block. Issues left: Accounts still show 0 balance as in screenshot above and Connection state always shows Connected with 0 peers which can't be correct as it syncs.

**Comment by almindor** [comment]
Well they improved then :) This should be considered a geth bug. All the values (account balance, syncing, peers) are taken directly from RPC calls to geth (if not using thin client). If you feel like it you can inspect them by turning on debug logging in the log tab and looking at the responses.

**Comment by UGatgithub** [comment]
No issue any longer, maybe it was some cache issue on my computers side. After a restart of the computer and Etherwall I get account data and peers count now, so finally it seems they have improved enough to be able to run in light mode connecting to a sufficient number of peers within a short period of time so I also close this one now.
