### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by zzzztj** [almindor/etherwall#87]
Hi - Firstly - thank you for the work you put into this.

I have a couple of issues though with the latest 2.2.1 with Geth 1.8.1 (not the Geth supplied)

Starting Geth with --syncmode fast --cache 1024 --rpc

I'm getting duplicate transactions entries, as per image.
Even when synced my balance is still showing zero, as per image

and additionally:  Is the circular busy graphic really necessary? Because it hits my graphics card for about 4Mh/s and it makes the app look nasty.

Thanks in advance

![etherwall1](https://user-images.githubusercontent.com/29117643/36947717-c57aa65a-200a-11e8-9bb6-b076a12354cc.JPG)

![etherwall2](https://user-images.githubusercontent.com/29117643/36947719-c732c6a8-200a-11e8-8ef0-883801b63be1.JPG)

**Comment by almindor** [comment]
Let's break this into three questions.

1. Why the double transactions
2. Why the 0 balance
3. Why the heavy busy indicator

First, I need to know your exact setup. What OS/version and settings are you running with? I suspect Windows 10 with a full node setup (run on the side with given params right?)

For 1. I think it's a bug. I noticed it sometimes on testnet but it was hard for me to reproduce. Not sure if it's related to your empty accounts tho, seems odd you'd get both.

The empty accounts is troubling. Are you sure geth was done syncing? What was the block # at the time? Was this working with previous EW version or previous geth version?

For 3. I didn't really realize that the busy indicator is so heavy. I have to provide some feedback for when either the backend is busy (thus operations cannot be performed) or geth is syncing so people don't e.g. attempt a tx send with old data (e.g. nonce or account balance being wrong).

I'll check it out and see if there's a more lightweight way with similar graphics :)

**Comment by almindor** [comment]
Also for 1. can you send me your registry entry for etherwall? You should be able to open `regedit` and then find `etherwall`. NOTE: it does not contain any passwords or such in any form but it does contain addresses and transaction history. If you want to keep it private you can scramble the addresses but I need the TX info intact. Feel free to encrypt and send to my email (almindor [at] gmail). I need to see if there are double entries saved.

**Comment by zzzztj** [comment]
Hi, thanks for the prompt reply.

You're correct, Win 10 latest updates.

Yes, It was (finally) fully synced. I've had lots of problems getting it synced with the bug that stopped geth from getting past around 380k.  This is actually the first time it's ever finally finished.

This seems to have been fixed with Geth 1.8.1 (previously was using 1.8.) I actually run Geth from system start up and a feature I'd love to see it to be able to connect to an already running Geth instead of the IPC in use error.  

When I use Etherwall I stop the system process from task manager and start it again with Etherwall. 

Reg attached.


[EtherDyne Reg.zip](https://github.com/almindor/etherwall/files/1779293/EtherDyne.Reg.zip)

TIA

**Comment by zzzztj** [comment]
Overnight the problem has got worse.
![etherwall3](https://user-images.githubusercontent.com/29117643/36955169-d45ec9e2-2061-11e8-97c5-9ae3f3d4a073.JPG)

**Comment by zzzztj** [comment]
Just discovered some more error logging. Not sure it's very helpful though :)
![etherwall4](https://user-images.githubusercontent.com/29117643/36956202-06a3320c-2068-11e8-9269-af64b132a744.JPG)

**Comment by almindor** [comment]
Those errors were from a geth crash on the server, should be fixed now. I'm still investigating the duplication of tx. entries.

**Comment by zzzztj** [comment]
I've upgraded geth to 1.8.2 but even on the console I can't see a balance.  Although I read somewhere that some calls have been removed from RPC and the errors I see do seem to be that: Haven't got it to hand here now, but it's something like Method not found on personal.unlockAccount("0xkkkkkkkk","password") call

As you say, the parse error has gone, but the duplications are still there.  Let me know if there's anything else you need to help.

**Comment by zzzztj** [comment]
Found out the problem with the zero balance is to do with the 'fast' mode.  Running as light has fixed that issue. The transaction appear to only be showing once now and are updating properly.  AND it's attaching correctly to an externally running geth.

So I think we can put this down to misconfiguration at my end.  

FTR My command line is now 

--cache 512 --rpc --datadir e:\ethereum --etherbase 0xFFFFFFFFFFFFF  --syncmode light  --verbosity 3  --nousb --identity IDENT

And remember - no Full or Fast on anything less than an SDD.

Thanks for your help

**Comment by almindor** [comment]
Hmm interesting. I'll close this issue now but am still wondering about the missing unlockAccount etc.

Also light mode is still experimental in geth be careful with it :)
