### ISSUE TITLE
SSL errors

### ISSUE THREAD

**Issue by SnaiLiuS** [almindor/etherwall#9]
Hello, after install etherwall 1.3.0+ i got erros in log:

Received: {"jsonrpc":"2.0","id":6,"result":"0x4a817c800"}
Response error: unknown error
HTTP Response parse error: недопустимое значение
HTTP Post reply: 
Sent: {
    "id": 6,
    "jsonrpc": "2.0",
    "method": "eth_gasPrice",
    "params": [
    ]
}

Connecting to IPC socket \\.\pipe\geth.ipc
Response parse error: недопустимое значение
HTTP Post reply: 
Response error: unknown error
HTTP Response parse error: недопустимое значение
HTTP Post reply: 
Checking to see if there is an already running geth...
Etherwall starting
HTTP Post request: {
}

HTTP Post request: {
    "currencies": [
        "EUR",
        "CAD",
        "USD",
        "GBP"
    ]
}

Problem solved after i put libeay32.dll and ssleay32.dll into etherwall folder. Please add these dll's into package. Windows vista64 here.

**Comment by almindor** [comment]
Hey thanks for reporting. It works without them for me on windows 8 but maybe they are included somehow on my system. I'm going to release 1.3.2 soon with some other bugfixes and will include the DLLs.

**Comment by SnaiLiuS** [comment]
maybe openssl installed?

**Comment by almindor** [comment]
I built the directory with the QT deployment tool which populates all the DLLs but there were always issues with extra missing ones in windows.

Now that I use HTTPS it's probable the missing SSL libs pop up. I either installed openSSL on my windows or maybe windows8+ has the DLLs in system now.

**Comment by SnaiLiuS** [comment]
ok, thanks for clarification. if my solution on putting missing dll into package will be good i hope to see it in next version

**Comment by almindor** [comment]
Ok thanks! Reopen if 1.3.2 still has the same issue. I should have it out soon.

**Comment by SnaiLiuS** [comment]
i will check 1.3.2+ without these DLL's on my system and comment the result

**Comment by almindor** [comment]
Just released 1.3.2

**Comment by SnaiLiuS** [comment]
I checked 1.3.2 version. It's ok with these DLL's (libeay32.dll and ssleay32.dll) that you have included into package. But without them the problem is the same in 1.3.2 with ssl to ethdata and currencies api:

Response error: unknown error
HTTP Response parse error: недопустимое значение
HTTP Post reply: 
Connecting to IPC socket \\.\pipe\geth.ipc
Response parse error: недопустимое значение
HTTP Post reply: 
Response error: unknown error
HTTP Response parse error: недопустимое значение
HTTP Post reply: 
Checking to see if there is an already running geth...
Etherwall starting
HTTP Post request: {
}

HTTP Post request: {
    "currencies": [
        "EUR",
        "CAD",
        "USD",
        "GBP"
    ]
}
