### ISSUE TITLE
Can´t connect to node 

### ISSUE THREAD

**Issue by Fank11** [almindor/etherwall#91]
**Hello, I can´t connect to the node. The log gives me the following info:
How can I save my wallets or fix this problem?
It seems like this does only happen in thin client mode but in thick client mode it doesn´t show any balances**
________________________________________________________________________________________
**GETH LOGH:**
INFO [05-15|16:45:49] RLPx listener up                         self="enode://407da2cce5f3ecb99f4544b9aea026538b45edea4c39cc9c79b048867eeb21725da768316826dd6a0e3eabf0109b19607f144a3d21a2134b1859c9628b8d0c22@[::]:30303?discport=0"
INFO [05-15|16:45:49] IPC endpoint opened                      url=/Users/anooob/Library/Ethereum/geth.ipc

INFO [05-15|16:45:49] Starting P2P networking 

INFO [05-15|16:45:49] Regenerated local transaction journal    transactions=0 accounts=0

INFO [05-15|16:45:49] Initialised chain configuration          config="{ChainID: 1 Homestead: 1150000 DAO: 1920000 DAOSupport: true EIP150: 2463000 EIP155: 2675000 EIP158: 2675000 Byzantium: 4370000 Constantinople: <nil> Engine: ethash}"
INFO [05-15|16:45:49] Disk storage enabled for ethash caches   dir=/Users/anooob/Library/Ethereum/geth/ethash count=3
INFO [05-15|16:45:49] Disk storage enabled for ethash DAGs     dir=/Users/anooob/.ethash                      count=2
INFO [05-15|16:45:49] Initialising Ethereum protocol           versions="[63 62]" network=1
INFO [05-15|16:45:49] Loaded most recent local header          number=223872 hash=9e11f6…07249d td=903048578861987775
INFO [05-15|16:45:49] Loaded most recent local full block      number=0      hash=d4e567…cb8fa3 td=17179869184
INFO [05-15|16:45:49] Loaded most recent local fast block      number=221953 hash=755bf2…add6d1 td=889936176783663165
INFO [05-15|16:45:49] Loaded local transaction journal         transactions=0 dropped=0

INFO [05-15|16:45:49] Maximum peer count                       ETH=0 LES=0 total=0
INFO [05-15|16:45:49] Starting peer-to-peer node               instance=Geth/v1.8.7-stable-66432f38/darwin-amd64/go1.10.1
INFO [05-15|16:45:49] Allocated cache and file handles         database=/Users/anooob/Library/Ethereum/geth/chaindata cache=384 handles=1024

________________________________________________________________________________________
**APP LOG:**

 Connected to IPC socket
Connecting to IPC socket /Users/anooob/Library/Ethereum/geth.ipc
Geth starting /Applications/Etherwall.app/Contents/MacOS/geth --syncmode=fast --cache 512 --datadir /Users/anooob/Library/Ethereum --nousb --maxpeers=0 --nodiscover --nat=none
Response error: unknown error
HTTP Response parse error: illegal value
HTTP Post reply: <html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>

Checking to see if there is an already running geth...
Etherwall starting
Response error: unknown error
HTTP Response parse error: illegal value
HTTP Post reply: <html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>

Response parse error: illegal value
HTTP Post reply: <html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>

Connecting to main Etherwall server
HTTP Post request: {
}

HTTP Post request: {
}

HTTP Post request: {
    "currencies": [
        "BTC",
        "EUR",
        "CAD",
        "USD",
        "GBP"
    ],
    "version": 2
}

**Comment by resplendenteye** [comment]
I am having the same issue.

**Comment by almindor** [comment]
The issue turned out to be a simple networking blip on the server. The "etherdata" master service failed to connect to the geth node two times in a row causing a crash. Systemd restarted the service but it quickly hit the max restarts settings and stopped trying.

I couldn't restart the service from abroad because I didn't take my ssh keys to the server with me.
I will create new issues to improve on both automatic and manual recovery to ensure this does not happen in the future.

The server is back to operational now.
